"""Shared helpers for the KML test modules.

These helpers build fire geometry and parse the generated KML back into
ElementTree so each test can assert on the document.
"""

from __future__ import annotations

import datetime
import struct
import typing

# The tests parse KML generated by the code under test, so the stdlib XML parser
# needs no defusedxml hardening.
import xml.etree.ElementTree as ET  # ruff: ignore[suspicious-xml-etree-import]
import zlib

import geopandas
import pytest
import shapely.geometry

import peri_scribe.kml_fire_data
import peri_scribe.kml_geometry
import peri_scribe.kml_plot_data
import peri_scribe.kml_plot_drawing
import peri_scribe.kml_plot_rendering
import peri_scribe.models


KML_NAMESPACE = "http://www.opengis.net/kml/2.2"

GX_NAMESPACE = "http://www.google.com/kml/ext/2.2"


def kml_tag(name: str) -> str:
    """Return the namespaced element tag for *name*.

    Args:
        name: The KML element name.

    Returns:
        The tag ElementTree uses for the element.
    """
    return f"{{{KML_NAMESPACE}}}{name}"


def gx_tag(name: str) -> str:
    """Return the namespaced element tag for the Google extension *name*.

    Args:
        name: The Google extension element name.

    Returns:
        The tag ElementTree uses for the element.
    """
    return f"{{{GX_NAMESPACE}}}{name}"


def square(side: float) -> shapely.geometry.Polygon:
    """Return a square of the given side, centered at the origin.

    Args:
        side: The length of each side.

    Returns:
        The square.
    """
    half = side / 2
    return shapely.geometry.box(-half, -half, half, half)


def perimeter_with_time(
    geometry: shapely.Geometry,
    observation_time: datetime.datetime | None = None,
) -> peri_scribe.kml_fire_data.Perimeter:
    """Build a perimeter with *geometry* and *observation_time*.

    Args:
        geometry: The perimeter geometry.
        observation_time: The perimeter's observation time, or None.

    Returns:
        The perimeter.
    """
    return peri_scribe.kml_fire_data.Perimeter(
        geometry=geometry,
        observation_time=observation_time,
    )


def geometry_frame(
    rows: list[tuple[str | None, str, shapely.geometry.base.BaseGeometry]],
    observation_times: list[datetime.datetime | None] | None = None,
    area_acres: list[float | None] | None = None,
) -> geopandas.GeoDataFrame:
    """Build a history GeoDataFrame from (identifier, name, geometry) rows.

    Args:
        rows: The identifier, name, and geometry of each row.
        observation_times: The observation time of each row, or None for every
            row when omitted.
        area_acres: The computed area of each row, or None to omit the column.

    Returns:
        The rows as a GeoDataFrame.
    """
    data: dict[str, object] = {
        "fire_identifier": [identifier for identifier, _name, _geometry in rows],
        "fire_name": [name for _identifier, name, _geometry in rows],
        "observation_time": (
            [None] * len(rows) if observation_times is None else observation_times
        ),
    }
    if area_acres is not None:
        data["area_acres"] = area_acres
    return geopandas.GeoDataFrame(
        data,
        geometry=[geometry for _identifier, _name, geometry in rows],
        crs="EPSG:4326",
    )


def fire_index_entry(
    name: str,
    status: typing.Literal["active", "inactive"],
    *,
    identifier: str | None = None,
    aliases: list[str] | None = None,
) -> peri_scribe.models.FireIndexEntry:
    """Build a fire index entry with empty paths.

    Args:
        name: The fire name.
        status: The fire status.
        identifier: The canonical identifier.
        aliases: Every alias identifier.

    Returns:
        The fire index entry.
    """
    return peri_scribe.models.FireIndexEntry(
        name=name,
        status=status,
        identifier=identifier,
        aliases=[] if aliases is None else aliases,
        paths=[],
    )


def fire_index(
    entries: list[peri_scribe.models.FireIndexEntry],
) -> peri_scribe.models.FireIndex:
    """Build a fire index from *entries*.

    Args:
        entries: The fire index entries.

    Returns:
        The fire index.
    """
    return peri_scribe.models.FireIndex(
        version="2026-08-18",
        fires=entries,
    )


def serial_plot_image_bundles(
    fire_bundles: tuple[
        tuple[str, tuple[peri_scribe.kml_plot_data.FirePlot, ...]],
        ...,
    ],
) -> tuple[tuple[peri_scribe.kml_plot_rendering.PlotImage, ...], ...]:
    """Render each fire's surviving plots in-process, without a process pool.

    A stand-in for the pool-based ``plot_image_bundles`` for tests that exercise the
    geometry and KML wiring around rendering rather than the pool itself.

    Args:
        fire_bundles: Each fire's filename prefix and its plots, in fire order.

    Returns:
        Each fire's rendered images, in the input order.
    """
    bundles = []
    for filename_prefix, plots in fire_bundles:
        images = []
        for plot in plots:
            series = peri_scribe.kml_plot_data.retained_series(plot.series)
            if not series:
                continue
            images.append(
                peri_scribe.kml_plot_rendering.PlotImage(
                    filename=peri_scribe.kml_plot_rendering.plot_filename(
                        filename_prefix,
                        plot.filename_suffix,
                    ),
                    content=peri_scribe.kml_plot_drawing.draw_plot(
                        peri_scribe.kml_plot_drawing.create_plot_renderer(),
                        series,
                        y_axis_label=plot.y_axis_label,
                    ),
                ),
            )
        bundles.append(tuple(images))
    return tuple(bundles)


def document_from(kml_text: str) -> ET.Element:
    """Parse *kml_text* and return its Document element.

    Args:
        kml_text: The KML document.

    Returns:
        The document element.
    """
    root = ET.fromstring(kml_text)  # ruff: ignore[suspicious-xml-element-tree-usage]
    document = root.find(kml_tag("Document"))
    if document is None:
        pytest.fail("KML has no Document element")
    return document


def document_from_writer(
    writer: peri_scribe.kml_geometry.KmlWriter,
) -> ET.Element:
    """Parse *writer*'s accumulated KML fragments into a document element.

    The writer holds document content without the enclosing ``<kml>`` and
    ``<Document>`` wrapper, so the wrapper is added here before parsing.

    Args:
        writer: The writer holding the KML content.

    Returns:
        The document element.
    """
    kml_text = (
        f'<kml xmlns="{KML_NAMESPACE}" xmlns:gx="{GX_NAMESPACE}">'
        f"<Document>{writer.text()}</Document></kml>"
    )
    return document_from(kml_text)


def folder_named(
    container: ET.Element,
    name: str,
) -> ET.Element:
    """Return the folder named *name* inside *container*.

    Args:
        container: The element to search.
        name: The folder name.

    Returns:
        The folder element.
    """
    for child in container:
        if child.tag == kml_tag("Folder") and child.findtext(kml_tag("name")) == name:
            return child
    pytest.fail(f"Folder {name!r} not found")


def placemark_named(folder: ET.Element, name: str) -> ET.Element:
    """Return the placemark named *name* inside *folder*.

    Args:
        folder: The folder to search.
        name: The placemark name.

    Returns:
        The placemark element.
    """
    for child in folder:
        if (
            child.tag == kml_tag("Placemark")
            and child.findtext(kml_tag("name")) == name
        ):
            return child
    pytest.fail(f"Placemark {name!r} not found")


def placemark_style_url(placemark: ET.Element) -> str:
    """Return the style URL of *placemark*.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The style URL.
    """
    style_url = placemark.findtext(kml_tag("styleUrl"))
    if style_url is None:
        pytest.fail("Placemark has no styleUrl")
    return style_url


def draw_order(placemark: ET.Element) -> int:
    """Return the gx:drawOrder of *placemark*'s geometry.

    A multi-geometry's order is set on each geometry it contains rather than on
    the multi-geometry itself, so the order is read from the first polygon.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The geometry's draw order.
    """
    for child in placemark:
        if child.tag == kml_tag("MultiGeometry"):
            for polygon in child:
                if polygon.tag != kml_tag("Polygon"):
                    continue
                text = polygon.findtext(gx_tag("drawOrder"))
                if text is None:
                    pytest.fail("MultiGeometry polygon has no gx:drawOrder")
                return int(text)
            pytest.fail("MultiGeometry has no polygons")
        if child.tag in {kml_tag("Point"), kml_tag("Polygon")}:
            text = child.findtext(gx_tag("drawOrder"))
            if text is None:
                pytest.fail("Placemark has no gx:drawOrder")
            return int(text)
    pytest.fail("Placemark has no geometry")


def visibility(feature: ET.Element) -> int | None:
    """Return the ``<visibility>`` of *feature*, or None when absent.

    A feature without a ``<visibility>`` element is visible by default.

    Args:
        feature: The folder or placemark to inspect.

    Returns:
        The visibility value, or None when the feature has none.
    """
    text = feature.findtext(kml_tag("visibility"))
    if text is None:
        return None
    return int(text)


def assert_tree_invisible(container: ET.Element) -> None:
    """Assert *container* and every feature beneath it is unchecked.

    Args:
        container: The folder whose whole tree must be invisible.
    """
    for feature in container.iter():
        if feature.tag not in {
            kml_tag("Folder"),
            kml_tag("Placemark"),
            gx_tag("Tour"),
        }:
            continue
        # Tour update instructions reuse Placemark and Folder tags but carry a
        # targetId rather than being real features, so they are not part of the
        # tree whose visibility is asserted here.
        if feature.get("targetId") is not None:
            continue
        assert visibility(feature) == 0, feature.findtext(kml_tag("name"))


def point_coordinates(placemark: ET.Element) -> tuple[float, float]:
    """Return the (longitude, latitude) of *placemark*'s point geometry.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The point's (longitude, latitude).
    """
    coordinates = placemark.find(f"{kml_tag('Point')}/{kml_tag('coordinates')}")
    if coordinates is None or coordinates.text is None:
        pytest.fail("Placemark has no point coordinates")
    longitude, latitude, *_altitude = coordinates.text.split(",")
    return float(longitude), float(latitude)


def exterior_coordinates(placemark: ET.Element) -> list[tuple[float, float]]:
    """Return the outer ring coordinates of *placemark*'s polygon.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The outer ring's (longitude, latitude) coordinates.
    """
    ring = placemark.find(
        f"{kml_tag('Polygon')}/{kml_tag('outerBoundaryIs')}/{kml_tag('LinearRing')}",
    )
    if ring is None:
        pytest.fail("Placemark has no polygon outer boundary")
    text = ring.findtext(kml_tag("coordinates"))
    if text is None:
        pytest.fail("Ring has no coordinates")
    return [
        (float(longitude), float(latitude))
        for longitude, latitude, *_altitude in (
            coordinates.split(",") for coordinates in text.split()
        )
    ]


def interior_coordinates(placemark: ET.Element) -> list[tuple[float, float]]:
    """Return the coordinates of *placemark*'s polygon hole, or [] when it has none.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The hole ring's (longitude, latitude) coordinates, or an empty list when the
        placemark's polygon is solid.
    """
    ring = placemark.find(
        f"{kml_tag('Polygon')}/{kml_tag('innerBoundaryIs')}/{kml_tag('LinearRing')}",
    )
    if ring is None:
        return []
    text = ring.findtext(kml_tag("coordinates"))
    if text is None:
        pytest.fail("Ring has no coordinates")
    return [
        (float(longitude), float(latitude))
        for longitude, latitude, *_altitude in (
            coordinates.split(",") for coordinates in text.split()
        )
    ]


def folder_names(container: ET.Element) -> list[str]:
    """Return the names of *container*'s folders, in order.

    Args:
        container: The element to inspect.

    Returns:
        The folder names.
    """
    names: list[str] = []
    for child in container:
        if child.tag != kml_tag("Folder"):
            continue
        name = child.findtext(kml_tag("name"))
        if name is not None:
            names.append(name)
    return names


def placemark_names(folder: ET.Element) -> list[str]:
    """Return the names of *folder*'s placemarks, in order.

    Args:
        folder: The folder to inspect.

    Returns:
        The placemark names.
    """
    names: list[str] = []
    for child in folder:
        if child.tag != kml_tag("Placemark"):
            continue
        name = child.findtext(kml_tag("name"))
        if name is not None:
            names.append(name)
    return names


def folder_item_icon_href(folder: ET.Element) -> str:
    """Return *folder*'s list-view item icon href.

    Args:
        folder: The folder to inspect.

    Returns:
        The icon href.
    """
    href = folder.findtext(
        f"{kml_tag('Style')}/{kml_tag('ListStyle')}"
        f"/{kml_tag('ItemIcon')}/{kml_tag('href')}",
    )
    if href is None:
        pytest.fail("Folder has no item icon")
    return href


def folder_list_item_type(folder: ET.Element) -> str | None:
    """Return *folder*'s list-view item type, or None when it has none.

    Args:
        folder: The folder to inspect.

    Returns:
        The list item type, like ``check`` or ``radioFolder``, or None when the folder
        sets no list item type.
    """
    return folder.findtext(
        f"{kml_tag('Style')}/{kml_tag('ListStyle')}/{kml_tag('listItemType')}",
    )


def top_level_folder(document: ET.Element) -> ET.Element:
    """Return the top-level folder holding the status folders in *document*.

    Args:
        document: The parsed KML document.

    Returns:
        The folder named after the document.
    """
    return folder_named(document, "PeriScribe Fires 2026")


def png_color(content: bytes) -> tuple[int, int, int]:
    """Return the RGB color of every pixel in the solid-color PNG *content*.

    Args:
        content: The PNG bytes.

    Returns:
        The (red, green, blue) color.
    """
    assert content[:8] == b"\x89PNG\r\n\x1a\n"
    width, height, bit_depth, color_type, _compression, _filter, _interlace = (
        struct.unpack(">IIBBBBB", content[16:29])
    )
    assert (bit_depth, color_type) == (8, 2)
    offset = 8
    idat = b""
    while offset < len(content):
        length = struct.unpack(">I", content[offset : offset + 4])[0]
        chunk_type = content[offset + 4 : offset + 8]
        if chunk_type == b"IDAT":
            idat += content[offset + 8 : offset + 8 + length]
        offset += 12 + length
    raw = zlib.decompress(idat)
    row_size = 1 + width * 3
    assert len(raw) == row_size * height
    color = (raw[1], raw[2], raw[3])
    for row_start in range(0, len(raw), row_size):
        assert raw[row_start] == 0
        for pixel_start in range(row_start + 1, row_start + row_size, 3):
            assert tuple(raw[pixel_start : pixel_start + 3]) == color
    return color


def png_pixel_rows(content: bytes) -> list[list[tuple[int, int, int, int]]]:
    """Return each row's RGBA pixels of the PNG *content*.

    Args:
        content: The PNG bytes.

    Returns:
        One list of (red, green, blue, alpha) tuples per row, top row first.
    """
    assert content[:8] == b"\x89PNG\r\n\x1a\n"
    width, height, bit_depth, color_type, _compression, _filter, _interlace = (
        struct.unpack(">IIBBBBB", content[16:29])
    )
    assert (bit_depth, color_type) == (8, 6)
    offset = 8
    idat = b""
    while offset < len(content):
        length = struct.unpack(">I", content[offset : offset + 4])[0]
        chunk_type = content[offset + 4 : offset + 8]
        if chunk_type == b"IDAT":
            idat += content[offset + 8 : offset + 8 + length]
        offset += 12 + length
    raw = zlib.decompress(idat)
    row_size = 1 + width * 4
    assert len(raw) == row_size * height
    rows: list[list[tuple[int, int, int, int]]] = []
    for row_start in range(0, len(raw), row_size):
        assert raw[row_start] == 0
        rows.append(
            [
                struct.unpack(">BBBB", raw[pixel_start : pixel_start + 4])
                for pixel_start in range(row_start + 1, row_start + row_size, 4)
            ],
        )
    return rows


def tour_named(folder: ET.Element, name: str) -> ET.Element:
    """Return the tour named *name* inside *folder*.

    Args:
        folder: The folder to search.
        name: The tour name.

    Returns:
        The tour element.
    """
    for child in folder:
        if child.tag == gx_tag("Tour") and child.findtext(kml_tag("name")) == name:
            return child
    pytest.fail(f"Tour {name!r} not found")


def tour_primitives(tour: ET.Element, tag: str) -> list[ET.Element]:
    """Return the playlist primitives with *tag* inside *tour*, in order.

    Args:
        tour: The tour element.
        tag: The primitive tag to collect.

    Returns:
        The matching playlist primitives.
    """
    playlist = tour.find(gx_tag("Playlist"))
    if playlist is None:
        pytest.fail("Tour has no playlist")
    return [child for child in playlist if child.tag == tag]


def update_visibility_by_target(update: ET.Element) -> dict[str, int]:
    """Return each targetId and its visibility in *update*'s change.

    Args:
        update: The animated update element.

    Returns:
        The visibility for each targetId.
    """
    change = update.find(f"{kml_tag('Update')}/{kml_tag('Change')}")
    if change is None:
        pytest.fail("Animated update has no change")
    visibility_by_target: dict[str, int] = {}
    for placemark in change.findall(kml_tag("Placemark")):
        target_id = placemark.get("targetId")
        if target_id is None:
            pytest.fail("Change placemark has no targetId")
        visibility = placemark.findtext(kml_tag("visibility"))
        if visibility is None:
            pytest.fail("Change placemark has no visibility")
        visibility_by_target[target_id] = int(visibility)
    return visibility_by_target


def wait_duration(wait: ET.Element) -> float:
    """Return the duration, in seconds, of *wait*.

    Args:
        wait: The wait element.

    Returns:
        The wait duration.
    """
    duration = wait.findtext(gx_tag("duration"))
    if duration is None:
        pytest.fail("Wait has no duration")
    return float(duration)
