"""Tests for peri_scribe.kml."""

from __future__ import annotations

import datetime
import json
import pathlib
import struct
import typing

# The tests parse KML generated by the code under test, so the stdlib XML parser
# needs no defusedxml hardening.
import xml.etree.ElementTree as ET  # ruff: ignore[suspicious-xml-etree-import]
import zipfile
import zlib

import geopandas
import pandas as pd
import pytest
import shapely.geometry
import simplekml

import peri_scribe.fire_history
import peri_scribe.fire_index
import peri_scribe.geo_package
import peri_scribe.kml
import peri_scribe.kml_plots
import peri_scribe.kml_template
import peri_scribe.kml_template_reader
import peri_scribe.models
import peri_scribe.perimeter_progression


YEAR = 2026

KML_NAMESPACE = "http://www.opengis.net/kml/2.2"

GX_NAMESPACE = "http://www.google.com/kml/ext/2.2"


def kml_tag(name: str) -> str:
    """Return the namespaced element tag for *name*.

    Args:
        name: The KML element name.

    Returns:
        The tag ElementTree uses for the element.
    """
    return f"{{{KML_NAMESPACE}}}{name}"


def gx_tag(name: str) -> str:
    """Return the namespaced element tag for the Google extension *name*.

    Args:
        name: The Google extension element name.

    Returns:
        The tag ElementTree uses for the element.
    """
    return f"{{{GX_NAMESPACE}}}{name}"


def square(side: float) -> shapely.geometry.Polygon:
    """Return a square of the given side, centered at the origin.

    Args:
        side: The length of each side.

    Returns:
        The square.
    """
    half = side / 2
    return shapely.geometry.box(-half, -half, half, half)


def perimeter_with_time(
    geometry: shapely.Geometry,
    observation_time: datetime.datetime | None = None,
) -> peri_scribe.kml.Perimeter:
    """Build a perimeter with *geometry* and *observation_time*.

    Args:
        geometry: The perimeter geometry.
        observation_time: The perimeter's observation time, or None.

    Returns:
        The perimeter.
    """
    return peri_scribe.kml.Perimeter(
        geometry=geometry,
        observation_time=observation_time,
    )


def geometry_frame(
    rows: list[tuple[str | None, str, shapely.geometry.base.BaseGeometry]],
    observation_times: list[datetime.datetime | None] | None = None,
) -> geopandas.GeoDataFrame:
    """Build a history GeoDataFrame from (identifier, name, geometry) rows.

    Args:
        rows: The identifier, name, and geometry of each row.
        observation_times: The observation time of each row, or None for every
            row when omitted.

    Returns:
        The rows as a GeoDataFrame.
    """
    return geopandas.GeoDataFrame(
        {
            "fire_identifier": [identifier for identifier, _name, _geometry in rows],
            "fire_name": [name for _identifier, name, _geometry in rows],
            "observation_time": (
                [None] * len(rows) if observation_times is None else observation_times
            ),
        },
        geometry=[geometry for _identifier, _name, geometry in rows],
        crs="EPSG:4326",
    )


def fire_index_entry(
    name: str,
    status: typing.Literal["active", "inactive"],
    *,
    identifier: str | None = None,
    aliases: list[str] | None = None,
) -> peri_scribe.models.FireIndexEntry:
    """Build a fire index entry with empty paths.

    Args:
        name: The fire name.
        status: The fire status.
        identifier: The canonical identifier.
        aliases: Every alias identifier.

    Returns:
        The fire index entry.
    """
    return peri_scribe.models.FireIndexEntry(
        name=name,
        status=status,
        identifier=identifier,
        aliases=[] if aliases is None else aliases,
        paths=[],
    )


def fire_index(
    entries: list[peri_scribe.models.FireIndexEntry],
) -> peri_scribe.models.FireIndex:
    """Build a fire index from *entries*.

    Args:
        entries: The fire index entries.

    Returns:
        The fire index.
    """
    return peri_scribe.models.FireIndex(
        version="2026-08-18",
        fires=entries,
    )


def serial_plot_image_bundles(
    fire_bundles: tuple[
        tuple[str, tuple[peri_scribe.kml_plots.FirePlot, ...]],
        ...,
    ],
) -> tuple[tuple[peri_scribe.kml_plots.PlotImage, ...], ...]:
    """Render each fire's surviving plots in-process, without a process pool.

    A stand-in for ``kml_plots.plot_image_bundles`` for tests that exercise the
    geometry and KML wiring around rendering rather than the pool itself.

    Args:
        fire_bundles: Each fire's filename prefix and its plots, in fire order.

    Returns:
        Each fire's rendered images, in the input order.
    """
    bundles = []
    for filename_prefix, plots in fire_bundles:
        images = []
        for plot in plots:
            series = peri_scribe.kml_plots.retained_series(plot.series)
            if not series:
                continue
            images.append(
                peri_scribe.kml_plots.PlotImage(
                    filename=peri_scribe.kml_plots.plot_filename(
                        filename_prefix,
                        plot.filename_suffix,
                    ),
                    content=peri_scribe.kml_plots.draw_plot(
                        peri_scribe.kml_plots.create_plot_renderer(),
                        series,
                        y_axis_label=plot.y_axis_label,
                    ),
                ),
            )
        bundles.append(tuple(images))
    return tuple(bundles)


@pytest.fixture
def in_process_plot_image_bundles(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Render plots in-process instead of in a pool for one test."""
    monkeypatch.setattr(
        peri_scribe.kml_plots,
        "plot_image_bundles",
        serial_plot_image_bundles,
    )


def document_from(kml_text: str) -> ET.Element:
    """Parse *kml_text* and return its Document element.

    Args:
        kml_text: The KML document.

    Returns:
        The document element.
    """
    root = ET.fromstring(kml_text)  # ruff: ignore[suspicious-xml-element-tree-usage]
    document = root.find(kml_tag("Document"))
    if document is None:
        pytest.fail("KML has no Document element")
    return document


def folder_named(
    container: ET.Element,
    name: str,
) -> ET.Element:
    """Return the folder named *name* inside *container*.

    Args:
        container: The element to search.
        name: The folder name.

    Returns:
        The folder element.
    """
    for child in container:
        if child.tag == kml_tag("Folder") and child.findtext(kml_tag("name")) == name:
            return child
    pytest.fail(f"Folder {name!r} not found")


def placemark_named(folder: ET.Element, name: str) -> ET.Element:
    """Return the placemark named *name* inside *folder*.

    Args:
        folder: The folder to search.
        name: The placemark name.

    Returns:
        The placemark element.
    """
    for child in folder:
        if (
            child.tag == kml_tag("Placemark")
            and child.findtext(kml_tag("name")) == name
        ):
            return child
    pytest.fail(f"Placemark {name!r} not found")


def placemark_style_url(placemark: ET.Element) -> str:
    """Return the style URL of *placemark*.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The style URL.
    """
    style_url = placemark.findtext(kml_tag("styleUrl"))
    if style_url is None:
        pytest.fail("Placemark has no styleUrl")
    return style_url


def draw_order(placemark: ET.Element) -> int:
    """Return the gx:drawOrder of *placemark*'s geometry.

    A multi-geometry's order is set on each geometry it contains rather than on
    the multi-geometry itself, so the order is read from the first polygon.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The geometry's draw order.
    """
    for child in placemark:
        if child.tag == kml_tag("MultiGeometry"):
            for polygon in child:
                if polygon.tag != kml_tag("Polygon"):
                    continue
                text = polygon.findtext(gx_tag("drawOrder"))
                if text is None:
                    pytest.fail("MultiGeometry polygon has no gx:drawOrder")
                return int(text)
            pytest.fail("MultiGeometry has no polygons")
        if child.tag in {kml_tag("Point"), kml_tag("Polygon")}:
            text = child.findtext(gx_tag("drawOrder"))
            if text is None:
                pytest.fail("Placemark has no gx:drawOrder")
            return int(text)
    pytest.fail("Placemark has no geometry")


def visibility(feature: ET.Element) -> int | None:
    """Return the ``<visibility>`` of *feature*, or None when absent.

    A feature without a ``<visibility>`` element is visible by default.

    Args:
        feature: The folder or placemark to inspect.

    Returns:
        The visibility value, or None when the feature has none.
    """
    text = feature.findtext(kml_tag("visibility"))
    if text is None:
        return None
    return int(text)


def assert_tree_invisible(container: ET.Element) -> None:
    """Assert *container* and every feature beneath it is unchecked.

    Args:
        container: The folder whose whole tree must be invisible.
    """
    for feature in container.iter():
        if feature.tag not in {
            kml_tag("Folder"),
            kml_tag("Placemark"),
            gx_tag("Tour"),
        }:
            continue
        # Tour update instructions reuse Placemark and Folder tags but carry a
        # targetId rather than being real features, so they are not part of the
        # tree whose visibility is asserted here.
        if feature.get("targetId") is not None:
            continue
        assert visibility(feature) == 0, feature.findtext(kml_tag("name"))


def point_coordinates(placemark: ET.Element) -> tuple[float, float]:
    """Return the (longitude, latitude) of *placemark*'s point geometry.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The point's (longitude, latitude).
    """
    coordinates = placemark.find(f"{kml_tag('Point')}/{kml_tag('coordinates')}")
    if coordinates is None or coordinates.text is None:
        pytest.fail("Placemark has no point coordinates")
    longitude, latitude, _altitude = coordinates.text.split(",")
    return float(longitude), float(latitude)


def exterior_coordinates(placemark: ET.Element) -> list[tuple[float, float]]:
    """Return the outer ring coordinates of *placemark*'s polygon.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The outer ring's (longitude, latitude) coordinates.
    """
    ring = placemark.find(
        f"{kml_tag('Polygon')}/{kml_tag('outerBoundaryIs')}/{kml_tag('LinearRing')}",
    )
    if ring is None:
        pytest.fail("Placemark has no polygon outer boundary")
    text = ring.findtext(kml_tag("coordinates"))
    if text is None:
        pytest.fail("Ring has no coordinates")
    return [
        (float(longitude), float(latitude))
        for longitude, latitude, _altitude in (
            coordinates.split(",") for coordinates in text.split()
        )
    ]


def interior_coordinates(placemark: ET.Element) -> list[tuple[float, float]]:
    """Return the coordinates of *placemark*'s polygon hole, or [] when it has none.

    Args:
        placemark: The placemark to inspect.

    Returns:
        The hole ring's (longitude, latitude) coordinates, or an empty list when the
        placemark's polygon is solid.
    """
    ring = placemark.find(
        f"{kml_tag('Polygon')}/{kml_tag('innerBoundaryIs')}/{kml_tag('LinearRing')}",
    )
    if ring is None:
        return []
    text = ring.findtext(kml_tag("coordinates"))
    if text is None:
        pytest.fail("Ring has no coordinates")
    return [
        (float(longitude), float(latitude))
        for longitude, latitude, _altitude in (
            coordinates.split(",") for coordinates in text.split()
        )
    ]


def folder_names(container: ET.Element) -> list[str]:
    """Return the names of *container*'s folders, in order.

    Args:
        container: The element to inspect.

    Returns:
        The folder names.
    """
    names: list[str] = []
    for child in container:
        if child.tag != kml_tag("Folder"):
            continue
        name = child.findtext(kml_tag("name"))
        if name is not None:
            names.append(name)
    return names


def placemark_names(folder: ET.Element) -> list[str]:
    """Return the names of *folder*'s placemarks, in order.

    Args:
        folder: The folder to inspect.

    Returns:
        The placemark names.
    """
    names: list[str] = []
    for child in folder:
        if child.tag != kml_tag("Placemark"):
            continue
        name = child.findtext(kml_tag("name"))
        if name is not None:
            names.append(name)
    return names


def folder_item_icon_href(folder: ET.Element) -> str:
    """Return *folder*'s list-view item icon href.

    Args:
        folder: The folder to inspect.

    Returns:
        The icon href.
    """
    href = folder.findtext(
        f"{kml_tag('Style')}/{kml_tag('ListStyle')}"
        f"/{kml_tag('ItemIcon')}/{kml_tag('href')}",
    )
    if href is None:
        pytest.fail("Folder has no item icon")
    return href


def png_color(content: bytes) -> tuple[int, int, int]:
    """Return the RGB color of every pixel in the solid-color PNG *content*.

    Args:
        content: The PNG bytes.

    Returns:
        The (red, green, blue) color.
    """
    assert content[:8] == b"\x89PNG\r\n\x1a\n"
    width, height, bit_depth, color_type, _compression, _filter, _interlace = (
        struct.unpack(">IIBBBBB", content[16:29])
    )
    assert (bit_depth, color_type) == (8, 2)
    offset = 8
    idat = b""
    while offset < len(content):
        length = struct.unpack(">I", content[offset : offset + 4])[0]
        chunk_type = content[offset + 4 : offset + 8]
        if chunk_type == b"IDAT":
            idat += content[offset + 8 : offset + 8 + length]
        offset += 12 + length
    raw = zlib.decompress(idat)
    row_size = 1 + width * 3
    assert len(raw) == row_size * height
    color = (raw[1], raw[2], raw[3])
    for row_start in range(0, len(raw), row_size):
        assert raw[row_start] == 0
        for pixel_start in range(row_start + 1, row_start + row_size, 3):
            assert tuple(raw[pixel_start : pixel_start + 3]) == color
    return color


def png_pixel_rows(content: bytes) -> list[list[tuple[int, int, int, int]]]:
    """Return each row's RGBA pixels of the PNG *content*.

    Args:
        content: The PNG bytes.

    Returns:
        One list of (red, green, blue, alpha) tuples per row, top row first.
    """
    assert content[:8] == b"\x89PNG\r\n\x1a\n"
    width, height, bit_depth, color_type, _compression, _filter, _interlace = (
        struct.unpack(">IIBBBBB", content[16:29])
    )
    assert (bit_depth, color_type) == (8, 6)
    offset = 8
    idat = b""
    while offset < len(content):
        length = struct.unpack(">I", content[offset : offset + 4])[0]
        chunk_type = content[offset + 4 : offset + 8]
        if chunk_type == b"IDAT":
            idat += content[offset + 8 : offset + 8 + length]
        offset += 12 + length
    raw = zlib.decompress(idat)
    row_size = 1 + width * 4
    assert len(raw) == row_size * height
    rows: list[list[tuple[int, int, int, int]]] = []
    for row_start in range(0, len(raw), row_size):
        assert raw[row_start] == 0
        rows.append(
            [
                struct.unpack(">BBBB", raw[pixel_start : pixel_start + 4])
                for pixel_start in range(row_start + 1, row_start + row_size, 4)
            ],
        )
    return rows


def tour_named(folder: ET.Element, name: str) -> ET.Element:
    """Return the tour named *name* inside *folder*.

    Args:
        folder: The folder to search.
        name: The tour name.

    Returns:
        The tour element.
    """
    for child in folder:
        if child.tag == gx_tag("Tour") and child.findtext(kml_tag("name")) == name:
            return child
    pytest.fail(f"Tour {name!r} not found")


def tour_primitives(tour: ET.Element, tag: str) -> list[ET.Element]:
    """Return the playlist primitives with *tag* inside *tour*, in order.

    Args:
        tour: The tour element.
        tag: The primitive tag to collect.

    Returns:
        The matching playlist primitives.
    """
    playlist = tour.find(gx_tag("Playlist"))
    if playlist is None:
        pytest.fail("Tour has no playlist")
    return [child for child in playlist if child.tag == tag]


def update_visibility_by_target(update: ET.Element) -> dict[str, int]:
    """Return each targetId and its visibility in *update*'s change.

    Args:
        update: The animated update element.

    Returns:
        The visibility for each targetId.
    """
    change = update.find(f"{kml_tag('Update')}/{kml_tag('Change')}")
    if change is None:
        pytest.fail("Animated update has no change")
    visibility_by_target: dict[str, int] = {}
    for placemark in change.findall(kml_tag("Placemark")):
        target_id = placemark.get("targetId")
        if target_id is None:
            pytest.fail("Change placemark has no targetId")
        visibility = placemark.findtext(kml_tag("visibility"))
        if visibility is None:
            pytest.fail("Change placemark has no visibility")
        visibility_by_target[target_id] = int(visibility)
    return visibility_by_target


def wait_duration(wait: ET.Element) -> float:
    """Return the duration, in seconds, of *wait*.

    Args:
        wait: The wait element.

    Returns:
        The wait duration.
    """
    duration = wait.findtext(gx_tag("duration"))
    if duration is None:
        pytest.fail("Wait has no duration")
    return float(duration)


def test_year_from_reads_directory_name() -> None:
    assert peri_scribe.kml.year_from(pathlib.Path(f"data/{YEAR}")) == YEAR


def test_kmz_filename_names_year() -> None:
    assert peri_scribe.kml.kmz_filename(2026) == "PeriScribe Fires 2026.kmz"


def test_kmz_path_places_file_in_maps_directory() -> None:
    assert peri_scribe.kml.kmz_path(pathlib.Path("data/2026")) == (
        pathlib.Path("data/2026/maps/PeriScribe Fires 2026.kmz")
    )


def test_identifiers_includes_identifier_and_aliases() -> None:
    entry = fire_index_entry(
        "Sorrento",
        "active",
        identifier="2026-casnd-150541",
        aliases=["2026-casnd-26150541", "guid"],
    )
    assert peri_scribe.kml.identifiers(entry) == {
        "2026-casnd-150541",
        "2026-casnd-26150541",
        "guid",
    }


def test_identifiers_omits_none_identifier() -> None:
    entry = fire_index_entry("Bug", "active", identifier=None)
    assert peri_scribe.kml.identifiers(entry) == frozenset()


def test_unique_filename_prefix_uses_identifier() -> None:
    assert (
        peri_scribe.kml.unique_filename_prefix(
            "id-bug",
            "Bug",
            frozenset(),
        )
        == "id-bug"
    )


def test_unique_filename_prefix_avoids_collisions() -> None:
    assert (
        peri_scribe.kml.unique_filename_prefix(
            None,
            "Bug",
            frozenset({"bug"}),
        )
        == "bug-2"
    )
    assert (
        peri_scribe.kml.unique_filename_prefix(
            None,
            "Bug",
            frozenset({"bug", "bug-2"}),
        )
        == "bug-3"
    )


def test_perimeter_groups_keys_by_identifier_and_preserves_order() -> None:
    first = square(1.0)
    second = square(2.0)
    nameless = square(3.0)
    first_time = datetime.datetime(2026, 8, 5, tzinfo=datetime.UTC)
    second_time = datetime.datetime(2026, 8, 6, tzinfo=datetime.UTC)
    perimeters = geometry_frame(
        [
            ("id-a", "Bug", first),
            ("id-a", "Bug", second),
            (None, "Nameless", nameless),
        ],
        observation_times=[first_time, second_time, None],
    )
    by_identifier, by_name = peri_scribe.kml.perimeter_groups(perimeters)
    assert by_identifier == {
        "id-a": [
            perimeter_with_time(first, first_time),
            perimeter_with_time(second, second_time),
        ],
    }
    assert by_name == {
        "Nameless": [perimeter_with_time(nameless, None)],
    }


def test_point_locations_keep_last_point_per_fire() -> None:
    earlier = shapely.geometry.Point(1.0, 1.0)
    later = shapely.geometry.Point(2.0, 2.0)
    points = geometry_frame([
        ("id-a", "Bug", earlier),
        ("id-a", "Bug", later),
        (None, "Nameless", shapely.geometry.Point(3.0, 3.0)),
    ])
    by_identifier, by_name = peri_scribe.kml.point_locations(points)
    assert by_identifier == {"id-a": later}
    assert list(by_name) == ["Nameless"]


def test_fire_point_matches_identifier() -> None:
    point = shapely.geometry.Point(1.0, 1.0)
    result = peri_scribe.kml.fire_point(
        frozenset({"id-a"}),
        "Bug",
        {"id-a": point},
        {},
    )
    assert result is point


def test_fire_point_falls_back_to_name() -> None:
    point = shapely.geometry.Point(1.0, 1.0)
    result = peri_scribe.kml.fire_point(
        frozenset(),
        "Bug",
        {},
        {"Bug": point},
    )
    assert result is point


def test_fire_point_returns_none_when_name_missing() -> None:
    assert peri_scribe.kml.fire_point(frozenset(), "Bug", {}, {}) is None


def test_fire_point_returns_none_when_identifier_missing() -> None:
    assert (
        peri_scribe.kml.fire_point(
            frozenset({"id-a"}),
            "Bug",
            {},
            {},
        )
        is None
    )


def test_fire_perimeters_matches_identifier() -> None:
    perimeters = (
        perimeter_with_time(square(1.0)),
        perimeter_with_time(square(2.0)),
    )
    result = peri_scribe.kml.fire_perimeters(
        frozenset({"id-a"}),
        "Bug",
        {"id-a": list(perimeters)},
        {},
    )
    assert result == perimeters


def test_fire_perimeters_falls_back_to_name() -> None:
    perimeters = (perimeter_with_time(square(1.0)),)
    result = peri_scribe.kml.fire_perimeters(
        frozenset(),
        "Bug",
        {},
        {"Bug": list(perimeters)},
    )
    assert result == perimeters


def test_fire_perimeters_returns_empty_when_unknown() -> None:
    assert (
        peri_scribe.kml.fire_perimeters(
            frozenset({"id-a"}),
            "Bug",
            {},
            {},
        )
        == ()
    )


def test_fire_geometries_matches_aliases_and_sorts_by_name() -> None:
    index = fire_index([
        fire_index_entry(
            "Sorrento",
            "active",
            identifier="2026-casnd-150541",
            aliases=["2026-casnd-26150541"],
        ),
        fire_index_entry("Bug", "inactive", identifier="id-bug"),
    ])
    sorrento_perimeter = square(3.0)
    perimeters = geometry_frame([
        ("2026-casnd-26150541", "Sorrento", sorrento_perimeter),
        ("id-bug", "Bug", square(1.0)),
    ])
    bug_point = shapely.geometry.Point(1.0, 1.0)
    points = geometry_frame([("id-bug", "Bug", bug_point)])
    fires = peri_scribe.kml.fire_geometries(
        index,
        perimeters,
        points,
        geometry_frame([]),
    )
    assert [fire.name for fire in fires] == ["Bug", "Sorrento"]
    bug, sorrento = fires
    assert bug.status is peri_scribe.models.FireStatus.INACTIVE
    assert bug.point is bug_point
    assert bug.perimeters == (perimeter_with_time(square(1.0)),)
    assert sorrento.status is peri_scribe.models.FireStatus.ACTIVE
    assert sorrento.point == sorrento_perimeter.representative_point()
    assert sorrento.perimeters == (perimeter_with_time(sorrento_perimeter),)


def test_fire_point_location_uses_known_point() -> None:
    point = shapely.geometry.Point(1.0, 1.0)
    result = peri_scribe.kml.fire_point_location(
        frozenset({"id-a"}),
        "Bug",
        {"id-a": point},
        {},
        (perimeter_with_time(square(2.0)),),
    )
    assert result is point


def test_fire_point_location_derives_point_from_latest_perimeter() -> None:
    earlier = square(1.0)
    latest = square(2.0)
    result = peri_scribe.kml.fire_point_location(
        frozenset({"id-a"}),
        "Bug",
        {},
        {},
        (
            perimeter_with_time(earlier),
            perimeter_with_time(latest),
        ),
    )
    assert result == latest.representative_point()


def test_fire_point_location_returns_none_without_geometry() -> None:
    assert (
        peri_scribe.kml.fire_point_location(
            frozenset({"id-a"}),
            "Bug",
            {},
            {},
            (),
        )
        is None
    )


def test_fire_geometries_derives_point_for_inactive_fire_without_location() -> None:
    index = fire_index([
        fire_index_entry("ALTA", "inactive", identifier="id-alta"),
    ])
    perimeter = square(2.0)
    fires = peri_scribe.kml.fire_geometries(
        index,
        geometry_frame([("id-alta", "ALTA", perimeter)]),
        geometry_frame([]),
        geometry_frame([]),
    )
    (fire,) = fires
    assert fire.status is peri_scribe.models.FireStatus.INACTIVE
    assert fire.point == perimeter.representative_point()
    assert fire.perimeters == (perimeter_with_time(perimeter),)


def test_fire_geometries_sorts_by_case_folded_name() -> None:
    index = fire_index([
        fire_index_entry(name, "active", identifier=f"id-{name}")
        for name in ("aB", "Ac", "AD", "ae")
    ])
    fires = peri_scribe.kml.fire_geometries(
        index,
        geometry_frame([]),
        geometry_frame([]),
        geometry_frame([]),
    )
    assert [fire.name for fire in fires] == ["aB", "Ac", "AD", "ae"]


def test_fire_geometries_attaches_plot_images(
    in_process_plot_image_bundles: None,
) -> None:
    index = fire_index([fire_index_entry("Bug", "active", identifier="id-bug")])
    perimeters = geometry_frame(
        [
            ("id-bug", "Bug", square(1.0)),
            ("id-bug", "Bug", square(2.0)),
        ],
        observation_times=[
            datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC),
            datetime.datetime(2026, 8, 6, 20, 0, tzinfo=datetime.UTC),
        ],
    )
    fires = peri_scribe.kml.fire_geometries(
        index,
        perimeters,
        geometry_frame([]),
        geometry_frame([]),
    )
    (fire,) = fires
    assert [image.filename for image in fire.images] == ["id-bug-perimeter.png"]
    assert fire.images[0].content
    assert fire.description is not None
    assert '<img src="id-bug-perimeter.png" />' in fire.description


def test_fire_geometries_skips_images_without_enough_dates() -> None:
    index = fire_index([fire_index_entry("Bug", "active", identifier="id-bug")])
    fires = peri_scribe.kml.fire_geometries(
        index,
        geometry_frame([("id-bug", "Bug", square(1.0))]),
        geometry_frame([]),
        geometry_frame([]),
    )
    (fire,) = fires
    assert fire.images == ()


def test_ring_coordinates_converts_coordinates() -> None:
    ring = shapely.geometry.LinearRing(
        [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0)],
    )
    assert peri_scribe.kml.ring_coordinates(ring) == [
        (0.0, 0.0),
        (1.0, 0.0),
        (1.0, 1.0),
        (0.0, 0.0),
    ]


def test_polygon_geometry_includes_holes() -> None:
    polygon = shapely.geometry.Polygon(
        [(0.0, 0.0), (0.0, 2.0), (2.0, 2.0), (2.0, 0.0), (0.0, 0.0)],
        [[(0.5, 0.5), (0.5, 1.5), (1.5, 1.5), (1.5, 0.5), (0.5, 0.5)]],
    )
    kml = simplekml.Kml()
    peri_scribe.kml.polygon_geometry(
        kml.document,
        "Bug",
        "#perimeter-fill",
        polygon,
        0,
        description=None,
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    assert exterior_coordinates(placemark) == [
        (0.0, 0.0),
        (0.0, 2.0),
        (2.0, 2.0),
        (2.0, 0.0),
        (0.0, 0.0),
    ]
    assert interior_coordinates(placemark) == [
        (0.5, 0.5),
        (0.5, 1.5),
        (1.5, 1.5),
        (1.5, 0.5),
        (0.5, 0.5),
    ]
    assert draw_order(placemark) == 0


def polygon_draw_orders(multi_geometry: ET.Element) -> list[int]:
    """Return the gx:drawOrder of each polygon in *multi_geometry*.

    Args:
        multi_geometry: The MultiGeometry element to inspect.

    Returns:
        The polygons' draw orders, in order.
    """
    orders: list[int] = []
    for polygon in multi_geometry:
        if polygon.tag != kml_tag("Polygon"):
            continue
        text = polygon.findtext(gx_tag("drawOrder"))
        if text is None:
            pytest.fail("MultiGeometry polygon has no gx:drawOrder")
        orders.append(int(text))
    return orders


def test_multi_polygon_geometry_holds_each_polygon() -> None:
    multi_polygon = shapely.geometry.MultiPolygon([
        shapely.geometry.box(0.0, 0.0, 1.0, 1.0),
        shapely.geometry.box(2.0, 2.0, 3.0, 3.0),
    ])
    expected_draw_order = 2
    kml = simplekml.Kml()
    peri_scribe.kml.multi_polygon_geometry(
        kml.document,
        "Bug",
        "#perimeter-fill",
        multi_polygon,
        expected_draw_order,
        description=None,
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    geometry = placemark.find(kml_tag("MultiGeometry"))
    if geometry is None:
        pytest.fail("Placemark has no MultiGeometry")
    polygons = [child for child in geometry if child.tag == kml_tag("Polygon")]
    assert len(polygons) == len(multi_polygon.geoms)
    assert geometry.find(gx_tag("drawOrder")) is None
    assert polygon_draw_orders(geometry) == [
        expected_draw_order,
        expected_draw_order,
    ]
    assert draw_order(placemark) == expected_draw_order


def test_perimeter_geometry_converts_polygon() -> None:
    kml = simplekml.Kml()
    peri_scribe.kml.perimeter_geometry(
        kml.document,
        "Bug",
        "#perimeter-fill",
        square(1.0),
        0,
        description=None,
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    assert placemark.find(kml_tag("Polygon")) is not None
    assert draw_order(placemark) == 0


def test_perimeter_geometry_converts_multi_polygon() -> None:
    multi_polygon = shapely.geometry.MultiPolygon([square(1.0), square(2.0)])
    expected_draw_order = 5
    kml = simplekml.Kml()
    peri_scribe.kml.perimeter_geometry(
        kml.document,
        "Bug",
        "#perimeter-fill",
        multi_polygon,
        expected_draw_order,
        description=None,
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    geometry = placemark.find(kml_tag("MultiGeometry"))
    if geometry is None:
        pytest.fail("Placemark has no MultiGeometry")
    assert geometry.find(gx_tag("drawOrder")) is None
    assert polygon_draw_orders(geometry) == [
        expected_draw_order,
        expected_draw_order,
    ]
    assert draw_order(placemark) == expected_draw_order


def test_point_placemark_names_and_styles_point() -> None:
    point = shapely.geometry.Point(1.0, 2.0)
    kml = simplekml.Kml()
    expected_draw_order = peri_scribe.kml_template.point_draw_order(3)
    peri_scribe.kml.point_placemark(
        kml.document,
        "Bug",
        "#point-icon",
        point,
        expected_draw_order,
        description=None,
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    assert placemark_style_url(placemark) == "#point-icon"
    assert point_coordinates(placemark) == (1.0, 2.0)
    assert draw_order(placemark) == expected_draw_order


def test_perimeter_placemark_names_and_styles_polygon() -> None:
    kml = simplekml.Kml()
    peri_scribe.kml.perimeter_placemark(
        kml.document,
        "Interior",
        "#perimeter-fill",
        square(1.0),
        0,
        description=None,
    )
    placemark = placemark_named(document_from(kml.kml()), "Interior")
    assert placemark_style_url(placemark) == "#perimeter-fill"
    assert placemark.find(kml_tag("Polygon")) is not None
    assert draw_order(placemark) == 0


def test_time_label_returns_none_without_observation_time() -> None:
    assert peri_scribe.kml.time_label(None) is None


def test_time_label_formats_california_time() -> None:
    observation_time = datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC)
    assert peri_scribe.kml.time_label(observation_time) == "08/05 13:30"


def test_interior_placemark_name_without_observation_time() -> None:
    assert peri_scribe.kml.interior_placemark_name(None) == "Interior"


def test_interior_placemark_name_with_observation_time() -> None:
    observation_time = datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC)
    assert peri_scribe.kml.interior_placemark_name(observation_time) == (
        "08/05 13:30 Interior"
    )


def test_mapping_placemark_name_without_observation_time() -> None:
    assert peri_scribe.kml.mapping_placemark_name(None) == "Unknown Mapping"


def test_mapping_placemark_name_with_observation_time() -> None:
    observation_time = datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC)
    assert peri_scribe.kml.mapping_placemark_name(observation_time) == (
        "08/05 13:30 Perimeter"
    )


def test_interior_ring_id_names_folder_and_index() -> None:
    kml = simplekml.Kml()
    folder = kml.document.newfolder(name="Bug")
    assert peri_scribe.kml.interior_ring_id(folder, 3) == (
        f"progression-ring-{folder.id}-3"
    )


def test_tour_wait_in_seconds_scales_days_by_playback_rate() -> None:
    earlier = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    later = datetime.datetime(2026, 8, 8, 20, 0, tzinfo=datetime.UTC)
    assert peri_scribe.kml.tour_wait_in_seconds(
        earlier,
        later,
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    ) == pytest.approx(3.0)
    assert peri_scribe.kml.tour_wait_in_seconds(
        earlier,
        later,
        0.5,
    ) == pytest.approx(1.5)


def test_tour_wait_in_seconds_with_missing_observation_time() -> None:
    observation_time = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    assert peri_scribe.kml.tour_wait_in_seconds(
        None,
        observation_time,
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    ) == pytest.approx(0.0)
    assert peri_scribe.kml.tour_wait_in_seconds(
        observation_time,
        None,
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    ) == pytest.approx(0.0)


def test_tour_seconds_per_day_for_short_fire() -> None:
    first = datetime.datetime(2026, 8, 1, 0, 0, tzinfo=datetime.UTC)
    second = datetime.datetime(2026, 8, 6, 0, 0, tzinfo=datetime.UTC)
    assert peri_scribe.kml.tour_seconds_per_day([first, second]) == pytest.approx(
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    )


def test_tour_seconds_per_day_for_five_day_fire() -> None:
    first = datetime.datetime(2026, 8, 1, 0, 0, tzinfo=datetime.UTC)
    second = datetime.datetime(2026, 8, 6, 0, 0, tzinfo=datetime.UTC)
    assert peri_scribe.kml.tour_seconds_per_day([first, second]) == pytest.approx(
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    )


def test_tour_seconds_per_day_for_long_fire() -> None:
    first = datetime.datetime(2026, 8, 1, 0, 0, tzinfo=datetime.UTC)
    second = datetime.datetime(2026, 8, 26, 0, 0, tzinfo=datetime.UTC)
    rate = peri_scribe.kml.tour_seconds_per_day([first, second])
    assert rate == pytest.approx(0.2)
    total_in_days = (second - first).total_seconds() / 86_400
    assert total_in_days * rate == pytest.approx(
        peri_scribe.kml.MAX_TOUR_PLAYBACK_IN_SECONDS,
    )


def test_tour_seconds_per_day_without_two_observations() -> None:
    observation_time = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    assert peri_scribe.kml.tour_seconds_per_day(
        [observation_time],
    ) == pytest.approx(peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY)
    assert peri_scribe.kml.tour_seconds_per_day([None]) == pytest.approx(
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    )
    assert peri_scribe.kml.tour_seconds_per_day([]) == pytest.approx(
        peri_scribe.kml.TOUR_PLAYBACK_SECONDS_PER_DAY,
    )


def test_visibility_change_reveals_rings_through_index() -> None:
    assert peri_scribe.kml.visibility_change(["a", "b", "c"], 1) == (
        '<Placemark targetId="a"><visibility>1</visibility></Placemark>'
        '<Placemark targetId="b"><visibility>1</visibility></Placemark>'
        '<Placemark targetId="c"><visibility>0</visibility></Placemark>'
    )


def test_progression_tour_reveals_rings_and_waits() -> None:
    first = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    second = datetime.datetime(2026, 8, 8, 20, 0, tzinfo=datetime.UTC)
    third = datetime.datetime(2026, 8, 9, 20, 0, tzinfo=datetime.UTC)
    ring_times = [first, second, third]
    kml = simplekml.Kml()
    folder = kml.document.newfolder(name="Bug")
    peri_scribe.kml.progression_tour(folder, ring_times)
    bug_folder = folder_named(document_from(kml.kml()), "Bug")
    tour = tour_named(bug_folder, "Progression")
    updates = tour_primitives(tour, gx_tag("AnimatedUpdate"))
    waits = tour_primitives(tour, gx_tag("Wait"))
    assert len(updates) == len(ring_times)
    assert len(waits) == len(ring_times)
    ring_ids = [
        peri_scribe.kml.interior_ring_id(folder, index)
        for index in range(len(ring_times))
    ]
    assert [update_visibility_by_target(update) for update in updates] == [
        {ring_ids[0]: 1, ring_ids[1]: 0, ring_ids[2]: 0},
        {ring_ids[0]: 1, ring_ids[1]: 1, ring_ids[2]: 0},
        {ring_ids[0]: 1, ring_ids[1]: 1, ring_ids[2]: 1},
    ]
    assert [wait_duration(wait) for wait in waits] == [3.0, 1.0, 1.0]


def test_progression_tour_scales_waits_for_long_fire() -> None:
    first = datetime.datetime(2026, 8, 1, 0, 0, tzinfo=datetime.UTC)
    second = datetime.datetime(2026, 8, 6, 0, 0, tzinfo=datetime.UTC)
    third = datetime.datetime(2026, 8, 26, 0, 0, tzinfo=datetime.UTC)
    ring_times = [first, second, third]
    kml = simplekml.Kml()
    folder = kml.document.newfolder(name="Bug")
    peri_scribe.kml.progression_tour(folder, ring_times)
    bug_folder = folder_named(document_from(kml.kml()), "Bug")
    tour = tour_named(bug_folder, "Progression")
    waits = tour_primitives(tour, gx_tag("Wait"))
    assert [wait_duration(wait) for wait in waits] == pytest.approx([1, 4, 1])


def test_assign_placemark_id_sets_placemark_id() -> None:
    kml = simplekml.Kml()
    folder = kml.document.newfolder(name="Bug")
    placemark = folder.newpolygon(
        name="Interior",
        outerboundaryis=[(0, 0), (1, 0), (1, 1), (0, 0)],
    )
    peri_scribe.kml.assign_placemark_id(placemark, "custom-id")
    interior = placemark_named(
        folder_named(document_from(kml.kml()), "Bug"),
        "Interior",
    )
    assert interior.get("id") == "custom-id"


@pytest.fixture
def style_urls() -> dict[str, str]:
    return peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    ).style_urls


def test_fire_folder_includes_point_and_progression(
    style_urls: dict[str, str],
) -> None:
    point = shapely.geometry.Point(1.0, 1.0)
    antepenultimate_time = datetime.datetime(2026, 8, 3, 23, 0, tzinfo=datetime.UTC)
    penultimate_time = datetime.datetime(2026, 8, 4, 16, 15, tzinfo=datetime.UTC)
    latest_time = datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC)
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=point,
        perimeters=(
            perimeter_with_time(square(1.0), antepenultimate_time),
            perimeter_with_time(square(2.0), penultimate_time),
            perimeter_with_time(square(3.0), latest_time),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    folder = folder_named(document_from(kml.kml()), "Bug")
    assert placemark_names(folder) == ["Bug"]
    perimeters_folder = folder_named(folder, "Perimeters")
    assert placemark_names(perimeters_folder) == [
        "08/05 13:30 Perimeter",
        "08/04 09:15 Perimeter",
        "08/03 16:00 Perimeter",
    ]
    assert folder_item_icon_href(perimeters_folder) == "perimeters.png"
    interior_folder = folder_named(folder, "Interior")
    assert placemark_names(interior_folder) == ["08/05 13:30 Interior"]
    assert folder_item_icon_href(interior_folder) == "interior.png"
    assert placemark_style_url(placemark_named(folder, "Bug")) == "#point-icon"
    assert (
        placemark_style_url(
            placemark_named(interior_folder, "08/05 13:30 Interior"),
        )
        == "#perimeter-fill"
    )
    assert {
        name: draw_order(placemark_named(container, name))
        for container, name in (
            (interior_folder, "08/05 13:30 Interior"),
            (perimeters_folder, "08/05 13:30 Perimeter"),
            (perimeters_folder, "08/04 09:15 Perimeter"),
            (perimeters_folder, "08/03 16:00 Perimeter"),
            (folder, "Bug"),
        )
    } == {
        "08/05 13:30 Interior": 0,
        "08/03 16:00 Perimeter": 1,
        "08/04 09:15 Perimeter": 2,
        "08/05 13:30 Perimeter": 3,
        "Bug": 4,
    }


def test_fire_folder_shows_only_available_perimeters(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(perimeter_with_time(square(1.0)),),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    folder = folder_named(document_from(kml.kml()), "Bug")
    assert placemark_names(folder) == ["Bug", "Unknown Mapping"]
    assert folder_names(folder) == ["Interior"]
    interior_folder = folder_named(folder, "Interior")
    assert placemark_names(interior_folder) == ["Interior"]
    assert {
        name: draw_order(placemark_named(container, name))
        for container, name in (
            (interior_folder, "Interior"),
            (folder, "Unknown Mapping"),
            (folder, "Bug"),
        )
    } == {
        "Interior": 0,
        "Unknown Mapping": 1,
        "Bug": 2,
    }


def test_fire_folder_draws_interior_from_difference_rings(
    style_urls: dict[str, str],
) -> None:
    first_time = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    second_time = datetime.datetime(2026, 8, 7, 20, 0, tzinfo=datetime.UTC)
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(
            perimeter_with_time(square(2.0), first_time),
            perimeter_with_time(square(4.0), second_time),
        ),
        progression_rings=(
            peri_scribe.perimeter_progression.Ring(
                geometry=square(1.0),
                observation_time=first_time,
            ),
            peri_scribe.perimeter_progression.Ring(
                geometry=square(2.0),
                observation_time=second_time,
            ),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    folder = folder_named(document_from(kml.kml()), "Bug")
    assert placemark_names(folder) == ["Bug"]
    perimeters_folder = folder_named(folder, "Perimeters")
    assert placemark_names(perimeters_folder) == [
        "08/07 13:00 Perimeter",
        "08/05 13:00 Perimeter",
    ]
    interior_folder = folder_named(folder, "Interior")
    assert placemark_names(interior_folder) == [
        "08/05 13:00 Interior",
        "08/07 13:00 Interior",
    ]
    first_interior = placemark_named(interior_folder, "08/05 13:00 Interior")
    second_interior = placemark_named(interior_folder, "08/07 13:00 Interior")
    assert placemark_style_url(first_interior) == "#perimeter-fill"
    assert placemark_style_url(second_interior) == "#perimeter-fill"
    assert {
        name: draw_order(placemark_named(interior_folder, name))
        for name in ("08/05 13:00 Interior", "08/07 13:00 Interior")
    } == {
        "08/05 13:00 Interior": 0,
        "08/07 13:00 Interior": 0,
    }
    # The rings fill the interior instead of the complete latest perimeter.
    assert set(exterior_coordinates(first_interior)) == {
        (-0.5, -0.5),
        (0.5, -0.5),
        (0.5, 0.5),
        (-0.5, 0.5),
    }
    assert set(exterior_coordinates(second_interior)) == {
        (-1.0, -1.0),
        (1.0, -1.0),
        (1.0, 1.0),
        (-1.0, 1.0),
    }


def test_fire_folder_falls_back_to_complete_perimeter_without_dated_rings(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(perimeter_with_time(square(1.0)),),
        progression_rings=(
            peri_scribe.perimeter_progression.Ring(
                geometry=square(1.0),
                observation_time=None,
            ),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    folder = folder_named(document_from(kml.kml()), "Bug")
    assert placemark_names(folder) == ["Bug", "Unknown Mapping"]
    assert placemark_names(folder_named(folder, "Interior")) == ["Interior"]


def test_fire_folder_without_point_or_perimeters_is_empty(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=None,
        perimeters=(),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    folder = folder_named(document_from(kml.kml()), "Bug")
    assert placemark_names(folder) == []
    assert folder_names(folder) == []


def test_fire_folder_leads_with_progression_tour(
    style_urls: dict[str, str],
) -> None:
    first_time = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    second_time = datetime.datetime(2026, 8, 7, 20, 0, tzinfo=datetime.UTC)
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(),
        progression_rings=(
            peri_scribe.perimeter_progression.Ring(
                geometry=square(1.0),
                observation_time=first_time,
            ),
            peri_scribe.perimeter_progression.Ring(
                geometry=square(2.0),
                observation_time=second_time,
            ),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    bug_folder = folder_named(document_from(kml.kml()), "Bug")
    features = [
        child
        for child in bug_folder
        if child.tag in {kml_tag("Folder"), kml_tag("Placemark"), gx_tag("Tour")}
    ]
    assert features[0].tag == gx_tag("Tour")
    tour = tour_named(bug_folder, "Progression")
    updates = tour_primitives(tour, gx_tag("AnimatedUpdate"))
    waits = tour_primitives(tour, gx_tag("Wait"))
    interior_folder = folder_named(bug_folder, "Interior")
    interior = [
        placemark_named(interior_folder, "08/05 13:00 Interior"),
        placemark_named(interior_folder, "08/07 13:00 Interior"),
    ]
    assert len(updates) == len(interior)
    assert len(waits) == len(interior)
    interior_ids = [placemark.get("id") for placemark in interior]
    assert [update_visibility_by_target(update) for update in updates] == [
        {interior_ids[0]: 1, interior_ids[1]: 0},
        {interior_ids[0]: 1, interior_ids[1]: 1},
    ]
    assert [wait_duration(wait) for wait in waits] == [2.0, 1.0]


def test_fire_folder_adds_tour_for_fallback_polygon(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(perimeter_with_time(square(1.0)),),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    bug_folder = folder_named(document_from(kml.kml()), "Bug")
    tour = tour_named(bug_folder, "Progression")
    updates = tour_primitives(tour, gx_tag("AnimatedUpdate"))
    waits = tour_primitives(tour, gx_tag("Wait"))
    assert len(updates) == 1
    assert len(waits) == 1
    assert [wait_duration(wait) for wait in waits] == [1.0]
    interior = placemark_named(folder_named(bug_folder, "Interior"), "Interior")
    assert update_visibility_by_target(updates[0]) == {interior.get("id"): 1}


def test_fire_folder_without_polygons_has_no_tour(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    bug_folder = folder_named(document_from(kml.kml()), "Bug")
    assert [child for child in bug_folder if child.tag == gx_tag("Tour")] == []


def test_latest_perimeters_folder_names_and_holds_fires(
    style_urls: dict[str, str],
) -> None:
    fires = [
        peri_scribe.kml.FireGeometry(
            name="Bug",
            status=peri_scribe.models.FireStatus.ACTIVE,
            point=None,
            perimeters=(),
        ),
    ]
    kml = simplekml.Kml()
    peri_scribe.kml.latest_perimeters_folder(kml.document, fires, style_urls)
    document = document_from(kml.kml())
    folder = folder_named(
        document,
        peri_scribe.kml_template.LATEST_PERIMETERS_FOLDER_NAME,
    )
    assert folder_names(folder) == ["Bug"]


def test_fire_geometries_includes_progression_rings() -> None:
    index = fire_index([
        fire_index_entry("Bug", "active", identifier="id-bug"),
    ])
    first_time = datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC)
    second_time = datetime.datetime(2026, 8, 7, 20, 0, tzinfo=datetime.UTC)
    rings = geometry_frame(
        [
            ("id-bug", "Bug", square(1.0)),
            ("id-bug", "Bug", square(2.0)),
        ],
        observation_times=[first_time, second_time],
    )
    fires = peri_scribe.kml.fire_geometries(
        index,
        geometry_frame([]),
        geometry_frame([]),
        rings,
    )
    (fire,) = fires
    assert fire.progression_rings == (
        peri_scribe.perimeter_progression.Ring(
            geometry=square(1.0),
            observation_time=first_time,
        ),
        peri_scribe.perimeter_progression.Ring(
            geometry=square(2.0),
            observation_time=second_time,
        ),
    )


def test_progression_folder_excludes_fires_without_rings(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.progression_folder(kml.document, [fire], style_urls)
    document = document_from(kml.kml())
    folder = folder_named(
        document,
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    assert folder_names(folder) == []


def test_progression_folder_holds_point_and_ring_folders(
    style_urls: dict[str, str],
) -> None:
    point = shapely.geometry.Point(1.0, 1.0)
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=point,
        perimeters=(),
        progression_rings=(
            peri_scribe.perimeter_progression.Ring(
                geometry=square(1.0),
                observation_time=datetime.datetime(
                    2026,
                    8,
                    13,
                    20,
                    0,
                    tzinfo=datetime.UTC,
                ),
            ),
            peri_scribe.perimeter_progression.Ring(
                geometry=square(2.0),
                observation_time=datetime.datetime(
                    2026,
                    8,
                    14,
                    20,
                    0,
                    tzinfo=datetime.UTC,
                ),
            ),
            peri_scribe.perimeter_progression.Ring(
                geometry=square(3.0),
                observation_time=datetime.datetime(
                    2026,
                    8,
                    15,
                    20,
                    0,
                    tzinfo=datetime.UTC,
                ),
            ),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.progression_folder(kml.document, [fire], style_urls)
    document = document_from(kml.kml())
    folder = folder_named(
        document,
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    bug_folder = folder_named(folder, "Bug")
    assert placemark_names(bug_folder) == ["Bug"]
    assert folder_names(bug_folder) == ["08/15", "08/13 - 08/14"]

    latest_folder = folder_named(bug_folder, "08/15")
    two_days_folder = folder_named(bug_folder, "08/13 - 08/14")
    assert placemark_names(latest_folder) == ["08/15 13:00 Interior"]
    assert placemark_names(two_days_folder) == [
        "08/13 13:00 Interior",
        "08/14 13:00 Interior",
    ]

    assert (
        placemark_style_url(
            placemark_named(latest_folder, "08/15 13:00 Interior"),
        )
        == "#days-fill-1"
    )
    assert (
        placemark_style_url(
            placemark_named(two_days_folder, "08/13 13:00 Interior"),
        )
        == "#days-fill-2"
    )
    assert (
        placemark_style_url(
            placemark_named(two_days_folder, "08/14 13:00 Interior"),
        )
        == "#days-fill-2"
    )

    assert {
        name: draw_order(placemark_named(container, name))
        for container, name in (
            (two_days_folder, "08/13 13:00 Interior"),
            (two_days_folder, "08/14 13:00 Interior"),
            (latest_folder, "08/15 13:00 Interior"),
            (bug_folder, "Bug"),
        )
    } == {
        "08/13 13:00 Interior": 0,
        "08/14 13:00 Interior": 1,
        "08/15 13:00 Interior": 2,
        "Bug": 3,
    }

    assert folder_item_icon_href(latest_folder) == "progression-band-1.png"
    assert folder_item_icon_href(two_days_folder) == "progression-band-2.png"

    assert set(
        exterior_coordinates(
            placemark_named(latest_folder, "08/15 13:00 Interior"),
        ),
    ) == {
        (-1.5, -1.5),
        (1.5, -1.5),
        (1.5, 1.5),
        (-1.5, 1.5),
    }
    assert set(
        exterior_coordinates(
            placemark_named(two_days_folder, "08/13 13:00 Interior"),
        ),
    ) == {
        (-0.5, -0.5),
        (0.5, -0.5),
        (0.5, 0.5),
        (-0.5, 0.5),
    }
    assert set(
        exterior_coordinates(
            placemark_named(two_days_folder, "08/14 13:00 Interior"),
        ),
    ) == {
        (-1.0, -1.0),
        (1.0, -1.0),
        (1.0, 1.0),
        (-1.0, 1.0),
    }


def test_progression_folder_leads_with_progression_tour(
    style_urls: dict[str, str],
) -> None:
    first_time = datetime.datetime(2026, 8, 13, 20, 0, tzinfo=datetime.UTC)
    second_time = datetime.datetime(2026, 8, 14, 20, 0, tzinfo=datetime.UTC)
    third_time = datetime.datetime(2026, 8, 15, 20, 0, tzinfo=datetime.UTC)
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(),
        progression_rings=(
            peri_scribe.perimeter_progression.Ring(
                geometry=square(1.0),
                observation_time=first_time,
            ),
            peri_scribe.perimeter_progression.Ring(
                geometry=square(2.0),
                observation_time=second_time,
            ),
            peri_scribe.perimeter_progression.Ring(
                geometry=square(3.0),
                observation_time=third_time,
            ),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.progression_folder(kml.document, [fire], style_urls)
    folder = folder_named(
        document_from(kml.kml()),
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    bug_folder = folder_named(folder, "Bug")
    features = [
        child
        for child in bug_folder
        if child.tag in {kml_tag("Folder"), kml_tag("Placemark"), gx_tag("Tour")}
    ]
    assert features[0].tag == gx_tag("Tour")
    tour = tour_named(bug_folder, "Progression")
    updates = tour_primitives(tour, gx_tag("AnimatedUpdate"))
    waits = tour_primitives(tour, gx_tag("Wait"))
    two_days_folder = folder_named(bug_folder, "08/13 - 08/14")
    latest_folder = folder_named(bug_folder, "08/15")
    # The rings live in different day-range subfolders, but the tour reveals them
    # in the same chronological order the latest-perimeters tour does.
    interior = [
        placemark_named(two_days_folder, "08/13 13:00 Interior"),
        placemark_named(two_days_folder, "08/14 13:00 Interior"),
        placemark_named(latest_folder, "08/15 13:00 Interior"),
    ]
    assert len(updates) == len(interior)
    assert len(waits) == len(interior)
    interior_ids = [placemark.get("id") for placemark in interior]
    assert [update_visibility_by_target(update) for update in updates] == [
        {interior_ids[0]: 1, interior_ids[1]: 0, interior_ids[2]: 0},
        {interior_ids[0]: 1, interior_ids[1]: 1, interior_ids[2]: 0},
        {interior_ids[0]: 1, interior_ids[1]: 1, interior_ids[2]: 1},
    ]
    assert [wait_duration(wait) for wait in waits] == [1.0, 1.0, 1.0]


def test_progression_folder_hides_its_tree(style_urls: dict[str, str]) -> None:
    point = shapely.geometry.Point(1.0, 1.0)
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=point,
        perimeters=(),
        progression_rings=(
            peri_scribe.perimeter_progression.Ring(
                geometry=square(1.0),
                observation_time=datetime.datetime(
                    2026,
                    8,
                    15,
                    20,
                    0,
                    tzinfo=datetime.UTC,
                ),
            ),
        ),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.progression_folder(kml.document, [fire], style_urls)
    document = document_from(kml.kml())
    folder = folder_named(
        document,
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    assert_tree_invisible(folder)


def test_fire_kml_includes_progression_maps_folder() -> None:
    index = fire_index([
        fire_index_entry("Bug", "active", identifier="id-bug"),
        fire_index_entry("ALTA", "inactive", identifier="id-alta"),
    ])
    observation_time = datetime.datetime(2026, 8, 15, 20, 0, tzinfo=datetime.UTC)
    perimeters = geometry_frame(
        [
            ("id-bug", "Bug", square(1.0)),
            ("id-alta", "ALTA", square(2.0)),
        ],
        observation_times=[observation_time, observation_time],
    )
    points = geometry_frame([
        ("id-bug", "Bug", shapely.geometry.Point(1.0, 1.0)),
        ("id-alta", "ALTA", shapely.geometry.Point(2.0, 2.0)),
    ])
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    fires = peri_scribe.kml.fire_geometries(
        index,
        perimeters,
        points,
        perimeters,
    )
    document = document_from(peri_scribe.kml.fire_kml(fires, template))

    active = folder_named(document, "Active Fires")
    active_progression = folder_named(
        active,
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    assert folder_names(active_progression) == ["Bug"]
    bug_folder = folder_named(active_progression, "Bug")
    assert placemark_names(bug_folder) == ["Bug"]
    assert folder_names(bug_folder) == ["08/15"]

    inactive = folder_named(document, "Inactive Fires")
    inactive_progression = folder_named(
        inactive,
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    assert folder_names(inactive_progression) == ["ALTA"]
    alta_folder = folder_named(inactive_progression, "ALTA")
    assert placemark_names(alta_folder) == ["ALTA"]
    assert folder_names(alta_folder) == ["08/15"]


def test_status_folder_name_for_active() -> None:
    assert (
        peri_scribe.kml.status_folder_name(
            peri_scribe.models.FireStatus.ACTIVE,
        )
        == "Active Fires"
    )


def test_status_folder_name_for_inactive() -> None:
    assert (
        peri_scribe.kml.status_folder_name(
            peri_scribe.models.FireStatus.INACTIVE,
        )
        == "Inactive Fires"
    )


def test_status_folder_filters_by_status(style_urls: dict[str, str]) -> None:
    active = peri_scribe.kml.FireGeometry(
        name="Active Fire",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=None,
        perimeters=(),
    )
    inactive = peri_scribe.kml.FireGeometry(
        name="Inactive Fire",
        status=peri_scribe.models.FireStatus.INACTIVE,
        point=None,
        perimeters=(),
    )
    kml = simplekml.Kml()
    peri_scribe.kml.status_folder(
        kml.document,
        [active, inactive],
        peri_scribe.models.FireStatus.ACTIVE,
        style_urls,
    )
    document = document_from(kml.kml())
    folder = folder_named(document, "Active Fires")
    perimeters_folder = folder_named(
        folder,
        peri_scribe.kml_template.LATEST_PERIMETERS_FOLDER_NAME,
    )
    assert folder_names(perimeters_folder) == ["Active Fire"]


def test_placemark_style_urls_descends_into_folders() -> None:
    document = document_from(peri_scribe.kml_template.template_kml())
    urls = peri_scribe.kml_template_reader.placemark_style_urls(document)
    assert urls["Point Location"] == "#point-icon"
    assert urls["Interior"] == "#perimeter-fill"
    assert urls["Latest Perimeter"] == "#perimeter-outline-1"
    assert urls["Penultimate Perimeter"] == "#perimeter-outline-2"
    assert urls["Antepenultimate Perimeter"] == "#perimeter-outline-3"


def test_collect_placemark_style_urls_skips_placemarks_without_style() -> None:
    document = ET.Element(kml_tag("Document"))
    folder = ET.SubElement(document, kml_tag("Folder"))
    ET.SubElement(folder, kml_tag("name")).text = "Folder"
    unstyled = ET.SubElement(folder, kml_tag("Placemark"))
    ET.SubElement(unstyled, kml_tag("name")).text = "Unstyled"
    unnamed = ET.SubElement(folder, kml_tag("Placemark"))
    ET.SubElement(unnamed, kml_tag("Point"))
    urls: dict[str, str] = {}
    peri_scribe.kml_template_reader.collect_placemark_style_urls(document, urls)
    assert urls == {}


def test_style_from_requires_style_id() -> None:
    style_element = ET.Element(kml_tag("Style"))
    with pytest.raises(ValueError, match="no id attribute"):
        peri_scribe.kml_template_reader.style_from(style_element)


def test_template_from_collects_styles_and_style_urls() -> None:
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    assert [style.id for style in template.styles] == [
        "point-icon",
        "perimeter-fill",
        "perimeter-outline-1",
        "perimeter-outline-2",
        "perimeter-outline-3",
        "days-fill-1",
        "days-fill-2",
        "days-fill-3",
        "days-fill-4",
        "days-fill-5",
        "days-fill-6",
        "days-fill-7",
        "days-fill-8",
    ]
    assert template.style_urls["Point Location"] == "#point-icon"


def test_template_from_requires_document() -> None:
    root = ET.Element(kml_tag("kml"))
    kml_text = ET.tostring(root, encoding="unicode")
    with pytest.raises(ValueError, match="no Document element"):
        peri_scribe.kml_template_reader.template_from(kml_text)


def test_read_template_reads_file(monkeypatch: pytest.MonkeyPatch) -> None:
    text = peri_scribe.kml_template.template_kml()

    def read_text(_self: pathlib.Path, encoding: str) -> str:
        assert encoding == "utf-8"
        return text

    monkeypatch.setattr(pathlib.Path, "read_text", read_text)
    template = peri_scribe.kml_template_reader.read_template(
        pathlib.Path("/templates/PeriScribe Template.kml"),
    )
    assert (
        template.style_urls
        == peri_scribe.kml_template_reader.template_from(text).style_urls
    )


def test_fire_kml_builds_active_and_inactive_folders(
    in_process_plot_image_bundles: None,
) -> None:
    index = fire_index([
        fire_index_entry("Bug", "active", identifier="id-bug"),
        fire_index_entry("ALTA", "inactive", identifier="id-alta"),
    ])
    perimeters = geometry_frame(
        [
            ("id-bug", "Bug", square(1.0)),
            ("id-bug", "Bug", square(2.0)),
            ("id-bug", "Bug", square(3.0)),
        ],
        observation_times=[
            datetime.datetime(2026, 8, 3, 23, 0, tzinfo=datetime.UTC),
            datetime.datetime(2026, 8, 4, 16, 15, tzinfo=datetime.UTC),
            datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC),
        ],
    )
    points = geometry_frame([
        ("id-bug", "Bug", shapely.geometry.Point(1.0, 1.0)),
        ("id-alta", "ALTA", shapely.geometry.Point(2.0, 2.0)),
    ])
    fires = peri_scribe.kml.fire_geometries(
        index,
        perimeters,
        points,
        geometry_frame([]),
    )
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    document = document_from(peri_scribe.kml.fire_kml(fires, template))

    assert folder_names(document) == ["Active Fires", "Inactive Fires"]
    active = folder_named(document, "Active Fires")
    active_perimeters = folder_named(
        active,
        peri_scribe.kml_template.LATEST_PERIMETERS_FOLDER_NAME,
    )
    bug_folder = folder_named(active_perimeters, "Bug")
    assert placemark_names(bug_folder) == ["Bug"]
    assert placemark_names(folder_named(bug_folder, "Perimeters")) == [
        "08/05 13:30 Perimeter",
        "08/04 09:15 Perimeter",
        "08/03 16:00 Perimeter",
    ]
    assert placemark_names(folder_named(bug_folder, "Interior")) == [
        "08/05 13:30 Interior",
    ]
    inactive = folder_named(document, "Inactive Fires")
    inactive_perimeters = folder_named(
        inactive,
        peri_scribe.kml_template.LATEST_PERIMETERS_FOLDER_NAME,
    )
    alta_folder = folder_named(inactive_perimeters, "ALTA")
    assert placemark_names(alta_folder) == ["ALTA"]
    assert draw_order(placemark_named(alta_folder, "ALTA")) == 1

    style_ids = {child.get("id") for child in document if child.tag == kml_tag("Style")}
    assert "point-icon" in style_ids
    assert "perimeter-fill" in style_ids
    assert "perimeter-outline-1" in style_ids


def test_fire_kml_hides_inactive_fires_tree(
    in_process_plot_image_bundles: None,
) -> None:
    index = fire_index([
        fire_index_entry("Bug", "active", identifier="id-bug"),
        fire_index_entry("ALTA", "inactive", identifier="id-alta"),
    ])
    observation_time = datetime.datetime(2026, 8, 15, 20, 0, tzinfo=datetime.UTC)
    perimeters = geometry_frame(
        [
            ("id-bug", "Bug", square(1.0)),
            ("id-alta", "ALTA", square(2.0)),
        ],
        observation_times=[observation_time, observation_time],
    )
    points = geometry_frame([
        ("id-bug", "Bug", shapely.geometry.Point(1.0, 1.0)),
        ("id-alta", "ALTA", shapely.geometry.Point(2.0, 2.0)),
    ])
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    fires = peri_scribe.kml.fire_geometries(
        index,
        perimeters,
        points,
        perimeters,
    )
    document = document_from(peri_scribe.kml.fire_kml(fires, template))

    inactive = folder_named(document, "Inactive Fires")
    assert_tree_invisible(inactive)

    active = folder_named(document, "Active Fires")
    active_perimeters = folder_named(
        active,
        peri_scribe.kml_template.LATEST_PERIMETERS_FOLDER_NAME,
    )
    bug_folder = folder_named(active_perimeters, "Bug")
    assert visibility(active) is None
    assert visibility(active_perimeters) is None
    assert visibility(bug_folder) is None
    for placemark in bug_folder.findall(kml_tag("Placemark")):
        assert visibility(placemark) is None
    assert visibility(tour_named(bug_folder, "Progression")) is None


def test_fire_kml_hides_active_progression_maps(
    in_process_plot_image_bundles: None,
) -> None:
    index = fire_index([
        fire_index_entry("Bug", "active", identifier="id-bug"),
        fire_index_entry("ALTA", "inactive", identifier="id-alta"),
    ])
    observation_time = datetime.datetime(2026, 8, 15, 20, 0, tzinfo=datetime.UTC)
    perimeters = geometry_frame(
        [
            ("id-bug", "Bug", square(1.0)),
            ("id-alta", "ALTA", square(2.0)),
        ],
        observation_times=[observation_time, observation_time],
    )
    points = geometry_frame([
        ("id-bug", "Bug", shapely.geometry.Point(1.0, 1.0)),
        ("id-alta", "ALTA", shapely.geometry.Point(2.0, 2.0)),
    ])
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    fires = peri_scribe.kml.fire_geometries(
        index,
        perimeters,
        points,
        perimeters,
    )
    document = document_from(peri_scribe.kml.fire_kml(fires, template))

    active = folder_named(document, "Active Fires")
    progression = folder_named(
        active,
        peri_scribe.perimeter_progression.PROGRESSION_MAPS_FOLDER_NAME,
    )
    assert_tree_invisible(progression)


def test_fire_kml_shows_derived_point_for_inactive_fire_without_location() -> None:
    index = fire_index([
        fire_index_entry("ALTA", "inactive", identifier="id-alta"),
    ])
    fires = peri_scribe.kml.fire_geometries(
        index,
        geometry_frame([("id-alta", "ALTA", square(2.0))]),
        geometry_frame([]),
        geometry_frame([]),
    )
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    document = document_from(peri_scribe.kml.fire_kml(fires, template))
    inactive = folder_named(document, "Inactive Fires")
    perimeters_folder = folder_named(
        inactive,
        peri_scribe.kml_template.LATEST_PERIMETERS_FOLDER_NAME,
    )
    alta_folder = folder_named(perimeters_folder, "ALTA")
    assert placemark_names(alta_folder) == ["ALTA", "Unknown Mapping"]
    assert placemark_names(folder_named(alta_folder, "Interior")) == ["Interior"]
    assert placemark_style_url(placemark_named(alta_folder, "ALTA")) == "#point-icon"


class FakeArchive:
    """In-memory zip archive stand-in that records its writes."""

    def __init__(self, *arguments: object, **keywords: object) -> None:
        self.arguments = arguments
        self.keywords = keywords
        self.writes: list[tuple[str, str | bytes]] = []

    def __enter__(self) -> typing.Self:
        return self

    def __exit__(
        self,
        _exc_type: object,
        _exc_value: object,
        _traceback: object,
    ) -> None:
        return None

    def writestr(self, name: str, data: str | bytes) -> None:
        self.writes.append((name, data))


def test_write_kmz_writes_compressed_document(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    path = pathlib.Path("/maps/PeriScribe Fires 2026.kmz")
    made_directories: list[pathlib.Path] = []
    archives: list[FakeArchive] = []

    def fake_zipfile(
        *arguments: object,
        **keywords: object,
    ) -> FakeArchive:
        archive = FakeArchive(*arguments, **keywords)
        archives.append(archive)
        return archive

    monkeypatch.setattr(
        pathlib.Path,
        "mkdir",
        lambda _self, **_keywords: made_directories.append(_self),
    )
    monkeypatch.setattr(zipfile, "ZipFile", fake_zipfile)

    peri_scribe.kml.write_kmz(path, "<kml/>")

    assert made_directories == [pathlib.Path("/maps")]
    assert len(archives) == 1
    archive = archives[0]
    assert archive.arguments == (path, "w")
    assert archive.keywords["compression"] == zipfile.ZIP_DEFLATED
    assert archive.keywords["compresslevel"] == zlib.Z_BEST_COMPRESSION
    assert archive.writes == [("doc.kml", "<kml/>")]


def test_write_kmz_writes_images(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    path = pathlib.Path("/maps/PeriScribe Fires 2026.kmz")
    archives: list[FakeArchive] = []

    def fake_zipfile(
        *arguments: object,
        **keywords: object,
    ) -> FakeArchive:
        archive = FakeArchive(*arguments, **keywords)
        archives.append(archive)
        return archive

    monkeypatch.setattr(
        pathlib.Path,
        "mkdir",
        lambda _self, **_keywords: None,
    )
    monkeypatch.setattr(zipfile, "ZipFile", fake_zipfile)

    image_content = b"\x89PNG\r\n\x1a\n"
    peri_scribe.kml.write_kmz(
        path,
        "<kml/>",
        {"id-bug-area.png": image_content},
    )

    (archive,) = archives
    assert archive.writes == [
        ("doc.kml", "<kml/>"),
        ("id-bug-area.png", image_content),
    ]


def test_progression_icon_filename_names_the_band() -> None:
    assert peri_scribe.kml.progression_icon_filename(0) == "progression-band-1.png"
    assert peri_scribe.kml.progression_icon_filename(7) == "progression-band-8.png"


def test_interior_icon_filename_names_the_folder() -> None:
    assert peri_scribe.kml.interior_icon_filename() == "interior.png"


def test_perimeters_icon_filename_names_the_folder() -> None:
    assert peri_scribe.kml.perimeters_icon_filename() == "perimeters.png"


def test_perimeters_icon_draws_two_full_width_lines() -> None:
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    rows = png_pixel_rows(peri_scribe.kml.perimeters_icon(template))
    side = peri_scribe.kml.PROGRESSION_ICON_SIDE_LENGTH_IN_PIXELS
    assert len(rows) == side
    top_line_row = side // 3
    bottom_line_row = side - 1 - side // 3
    background = (0x32, 0x4B, 0x32, 255)
    for row_index, row in enumerate(rows):
        if row_index == top_line_row:
            assert row == [(255, 0, 0, 255)] * side
        elif row_index == bottom_line_row:
            assert row == [(255, 255, 0, 255)] * side
        else:
            assert row == [background] * side


def test_perimeters_icon_colors_come_from_template() -> None:
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    styles = {style.id: style for style in template.styles}
    latest_style_id = template.style_urls["Latest Perimeter"].lstrip("#")
    penultimate_style_id = template.style_urls["Penultimate Perimeter"].lstrip("#")
    styles[latest_style_id].linestyle.color = "ff00ff00"
    styles[penultimate_style_id].linestyle.color = "ffff0000"
    rows = png_pixel_rows(peri_scribe.kml.perimeters_icon(template))
    side = peri_scribe.kml.PROGRESSION_ICON_SIDE_LENGTH_IN_PIXELS
    assert rows[side // 3] == [(0, 255, 0, 255)] * side
    assert rows[side - 1 - side // 3] == [(0, 0, 255, 255)] * side


def test_kml_color_rgb_decodes_aabbggrr() -> None:
    assert peri_scribe.kml.kml_color_rgb("7f002aff") == (255, 42, 0)
    assert peri_scribe.kml.kml_color_rgb("7fbdb7b0") == (176, 183, 189)


def test_solid_color_png_fills_a_square() -> None:
    content = peri_scribe.kml.solid_color_png(1, 2, 3, 4)
    assert png_color(content) == (1, 2, 3)


def test_interior_icon_matches_template_color() -> None:
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    assert png_color(peri_scribe.kml.interior_icon(template)) == (255, 0, 0)


def test_progression_icons_match_template_colors() -> None:
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    icons = peri_scribe.kml.progression_icons(template)
    assert set(icons) == {
        peri_scribe.kml.progression_icon_filename(index)
        for index in range(len(peri_scribe.perimeter_progression.PROGRESSION_BANDS))
    }
    assert png_color(icons["progression-band-1.png"]) == (255, 42, 0)
    assert png_color(icons["progression-band-8.png"]) == (176, 183, 189)


def test_create_kmz_reads_history_and_writes_kmz(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    year_directory = pathlib.Path("data/2026")
    index = fire_index([
        fire_index_entry("Bug", "active", identifier="id-bug"),
    ])
    monkeypatch.setattr(
        peri_scribe.fire_index,
        "load_fire_index",
        lambda _directory: index,
    )
    monkeypatch.setattr(
        peri_scribe.fire_history,
        "history_geopackage_path",
        lambda _directory: pathlib.Path("/derived/full.gpkg"),
    )
    perimeters = geometry_frame([("id-bug", "Bug", square(1.0))])
    points = geometry_frame([
        ("id-bug", "Bug", shapely.geometry.Point(1.0, 1.0)),
    ])

    def read_layer(
        _path: pathlib.Path,
        layer_name: str,
    ) -> geopandas.GeoDataFrame:
        return perimeters if layer_name == "perimeter_history" else points

    monkeypatch.setattr(peri_scribe.geo_package, "read_layer", read_layer)
    template = peri_scribe.kml_template_reader.template_from(
        peri_scribe.kml_template.template_kml(),
    )
    monkeypatch.setattr(
        peri_scribe.kml_template_reader,
        "read_template",
        lambda _path: template,
    )
    writes: list[tuple[pathlib.Path, str, dict[str, bytes]]] = []
    monkeypatch.setattr(
        peri_scribe.kml,
        "write_kmz",
        lambda path, kml_text, images: writes.append((path, kml_text, images)),
    )

    result = peri_scribe.kml.create_kmz(year_directory)

    assert result == peri_scribe.kml.kmz_path(year_directory)
    assert len(writes) == 1
    path, kml_text, images = writes[0]
    assert path == result
    assert "Active Fires" in kml_text
    assert set(images) == {
        peri_scribe.kml.interior_icon_filename(),
        peri_scribe.kml.perimeters_icon_filename(),
        *(
            peri_scribe.kml.progression_icon_filename(index)
            for index in range(len(peri_scribe.perimeter_progression.PROGRESSION_BANDS))
        ),
    }
    assert all(content.startswith(b"\x89PNG\r\n\x1a\n") for content in images.values())


def description_perimeter_frame() -> geopandas.GeoDataFrame:
    """Return a perimeter history frame with attribute columns populated.

    Returns:
        The frame.
    """
    return geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-bug", "id-bug"],
            "fire_name": ["Bug", "Bug"],
            "source": ["firis_perimeter", "firis_perimeter"],
            "mission": ["CA-BUG-1", "CA-BUG-2"],
            "area_acres": [10.0, 20.0],
            "percent_contained": [10.0, 20.0],
            "estimated_cost_to_date": [1000.0, 2000.0],
            "estimated_final_cost": [1500.0, 2500.0],
            "discovery_time": [
                datetime.datetime(2026, 6, 29, 12, 4, 46, tzinfo=datetime.UTC),
                datetime.datetime(2026, 6, 29, 12, 4, 46, tzinfo=datetime.UTC),
            ],
            "observation_time": [
                datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC),
                datetime.datetime(2026, 8, 6, 20, 0, tzinfo=datetime.UTC),
            ],
            "source_attributes": [
                json.dumps(
                    {
                        "attr_InitialResponseDateTime": "2026-07-27T19:24:00",
                        "attr_IncidentComplexityLevel": "Type 4 Incident",
                        "attr_PrimaryFuelModel": "Timber (Litter and Understory)",
                        "attr_PredominantFuelModel": "GS1",
                        "attr_PredominantFuelGroup": "Grass",
                        "attr_FireBehaviorGeneral": "Active",
                        "attr_FireBehaviorGeneral2": "Running",
                        "attr_POOLandownerCategory": "Federal",
                    },
                ),
                json.dumps(
                    {
                        "attr_InitialResponseDateTime": "2026-07-27T19:24:00",
                        "attr_IncidentComplexityLevel": "Type 4 Incident",
                        "attr_PrimaryFuelModel": "Timber (Litter and Understory)",
                        "attr_PredominantFuelModel": "GS1",
                        "attr_PredominantFuelGroup": "Grass",
                        "attr_FireBehaviorGeneral": "Active",
                        "attr_FireBehaviorGeneral2": "Running",
                        "attr_POOLandownerCategory": "Federal",
                    },
                ),
            ],
        },
        geometry=[square(1.0), square(2.0)],
        crs="EPSG:4326",
    )


def description_point_frame() -> geopandas.GeoDataFrame:
    """Return a point history frame with attribute columns populated.

    Returns:
        The frame.
    """
    return geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-bug"],
            "fire_name": ["Bug"],
            "incident_size": [30.0],
            "percent_contained": [30.0],
            "estimated_cost_to_date": [3000.0],
            "estimated_final_cost": [3500.0],
            "discovery_time": [
                datetime.datetime(2026, 6, 29, 12, 4, 46, tzinfo=datetime.UTC),
            ],
            "observation_time": [
                datetime.datetime(2026, 8, 6, 20, 0, tzinfo=datetime.UTC),
            ],
            "source_attributes": [
                json.dumps(
                    {
                        "POOJurisdictionalUnit": "CANOD",
                        "InitialResponseDateTime": "2026-07-27T19:24:00",
                        "IncidentTypeCategory": "WF",
                        "IncidentComplexityLevel": "Type 4 Incident",
                        "FireMgmtComplexity": "Type 5 Incident",
                        "OrganizationalAssessment": "Type 3 IC",
                        "SecondaryFuelModel": "Brush (2 feet)",
                        "PredominantFuelModel": "GS1",
                        "PredominantFuelGroup": "Grass",
                        "FireBehaviorGeneral": "Active",
                        "FireBehaviorGeneral1": "Creeping",
                        "FireBehaviorGeneral2": "Smoldering",
                        "FireBehaviorGeneral3": "Smoldering",
                    },
                ),
            ],
        },
        geometry=[shapely.geometry.Point(1.0, 1.0)],
        crs="EPSG:4326",
    )


def test_latest_matching_row_matches_by_identifier() -> None:
    later = datetime.datetime(2026, 8, 6, 20, 0, tzinfo=datetime.UTC)
    frame = geometry_frame(
        [
            ("id-a", "Bug", square(1.0)),
            ("id-a", "Bug", square(2.0)),
        ],
        observation_times=[
            datetime.datetime(2026, 8, 5, 20, 0, tzinfo=datetime.UTC),
            later,
        ],
    )
    row = peri_scribe.kml.latest_matching_row(frame, frozenset({"id-a"}), "Bug")
    assert row is not None
    assert row["observation_time"] == later


def test_latest_matching_row_matches_by_name_without_identifier() -> None:
    frame = geometry_frame([
        (None, "Bug", square(1.0)),
        (None, "Bug", square(2.0)),
    ])
    row = peri_scribe.kml.latest_matching_row(frame, frozenset(), "Bug")
    assert row is not None
    assert row["fire_name"] == "Bug"


def test_latest_matching_row_returns_none_without_match() -> None:
    frame = geometry_frame([("id-a", "Bug", square(1.0))])
    assert (
        peri_scribe.kml.latest_matching_row(
            frame,
            frozenset({"id-b"}),
            "Bug",
        )
        is None
    )


def test_column_value_returns_none_for_missing_row_or_column() -> None:
    frame = geometry_frame([("id-a", "Bug", square(1.0))])
    row = frame.iloc[0]
    assert peri_scribe.kml.column_value(row, "fire_name") == "Bug"
    assert peri_scribe.kml.column_value(row, "not_a_column") is None
    assert peri_scribe.kml.column_value(None, "fire_name") is None


def test_text_value_returns_none_for_blank() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "mission": ["  "],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    row = frame.iloc[0]
    assert peri_scribe.kml.text_value(row, "mission") is None
    assert peri_scribe.kml.text_value(row, "fire_name") == "Bug"
    assert peri_scribe.kml.text_value(None, "fire_name") is None


def test_float_value_reads_numbers_and_rejects_non_numeric() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "area_acres": [12.5],
            "mission": ["x"],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    row = frame.iloc[0]
    assert peri_scribe.kml.float_value(row, "area_acres") == pytest.approx(12.5)
    assert peri_scribe.kml.float_value(row, "mission") is None
    assert peri_scribe.kml.float_value(None, "area_acres") is None


def test_as_datetime_parses_strings_and_timestamps() -> None:
    expected = datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC)
    assert peri_scribe.kml.as_datetime(None) is None
    assert peri_scribe.kml.as_datetime("2026-08-05T20:30:00Z") == expected
    assert peri_scribe.kml.as_datetime(pd.Timestamp("2026-08-05T20:30:00Z")) == expected
    assert peri_scribe.kml.as_datetime("not a date") is None


def test_datetime_value_reads_a_column() -> None:
    expected = datetime.datetime(2026, 8, 5, 20, 30, tzinfo=datetime.UTC)
    frame = geometry_frame(
        [("id-a", "Bug", square(1.0))],
        observation_times=[expected],
    )
    assert peri_scribe.kml.datetime_value(frame.iloc[0], "observation_time") == expected
    assert peri_scribe.kml.datetime_value(None, "observation_time") is None


def test_source_attribute_value_reads_json() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [json.dumps({"POOJurisdictionalUnit": "CANOD"})],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    assert (
        peri_scribe.kml.source_attribute_value(
            frame.iloc[0],
            "POOJurisdictionalUnit",
        )
        == "CANOD"
    )
    assert peri_scribe.kml.source_attribute_value(frame.iloc[0], "Missing") is None
    assert peri_scribe.kml.source_attribute_value(None, "POOJurisdictionalUnit") is None


def test_source_attribute_value_rejects_invalid_json() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": ["not json"],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    assert peri_scribe.kml.source_attribute_value(frame.iloc[0], "X") is None


def test_source_attribute_value_accepts_decoded_dict() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [{"POOJurisdictionalUnit": "CANOD"}],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    assert (
        peri_scribe.kml.source_attribute_value(
            frame.iloc[0],
            "POOJurisdictionalUnit",
        )
        == "CANOD"
    )


def test_source_attribute_value_rejects_non_dict_json() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [json.dumps(["a", "b"])],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    assert peri_scribe.kml.source_attribute_value(frame.iloc[0], "X") is None


def test_source_text_value_returns_none_for_blank() -> None:
    frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [json.dumps({"Unit": "  "})],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    assert peri_scribe.kml.source_text_value(frame.iloc[0], "Unit") is None
    assert peri_scribe.kml.source_text_value(frame.iloc[0], "Missing") is None


def test_numbered_source_text_orders_by_slot_number_and_dedupes() -> None:
    perimeter = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [
                json.dumps(
                    {
                        "attr_FireBehaviorGeneral": "Active",
                        "attr_FireBehaviorGeneral2": "Running",
                    },
                ),
            ],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    point = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [
                json.dumps(
                    {
                        "FireBehaviorGeneral2": "Running",
                        "FireBehaviorGeneral3": "Smoldering",
                    },
                ),
            ],
        },
        geometry=[shapely.geometry.Point(1.0, 1.0)],
        crs="EPSG:4326",
    )
    assert (
        peri_scribe.kml.numbered_source_text(
            perimeter.iloc[0],
            point.iloc[0],
            peri_scribe.kml.FIRE_BEHAVIOR_ATTRIBUTE_KEYS,
        )
        == "Active; Running; Smoldering"
    )
    empty = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-a"],
            "fire_name": ["Bug"],
            "source_attributes": [json.dumps({})],
        },
        geometry=[shapely.geometry.Point(1.0, 1.0)],
        crs="EPSG:4326",
    )
    assert (
        peri_scribe.kml.numbered_source_text(
            None,
            empty.iloc[0],
            peri_scribe.kml.FIRE_BEHAVIOR_ATTRIBUTE_KEYS,
        )
        is None
    )


def test_source_label_names_known_sources() -> None:
    assert peri_scribe.kml.source_label("firis_perimeter") == "FIRIS / NIFC"
    assert peri_scribe.kml.source_label("wfigs_perimeter") == "WFIGS"
    assert peri_scribe.kml.source_label("unknown") is None
    assert peri_scribe.kml.source_label(None) is None


def test_fire_description_prefers_latest_perimeter_values() -> None:
    entry = fire_index_entry("Bug", "active", identifier="id-bug")
    description = peri_scribe.kml.fire_description(
        entry,
        description_perimeter_frame(),
        description_point_frame(),
    )
    assert description.area_in_acres == pytest.approx(20.0)
    assert description.percent_contained == pytest.approx(20.0)
    assert description.estimated_cost_to_date_in_dollars == pytest.approx(2000.0)
    assert description.estimated_final_cost_in_dollars == pytest.approx(2500.0)
    assert description.mission == "CA-BUG-2"
    assert description.source == "FIRIS / NIFC"
    assert description.identifier == "id-bug"
    assert description.observation_time == datetime.datetime(
        2026,
        8,
        6,
        20,
        0,
        tzinfo=datetime.UTC,
    )
    assert description.initial_response_time == datetime.datetime(
        2026,
        7,
        27,
        19,
        24,
        tzinfo=datetime.UTC,
    )
    assert description.protecting_unit == "CANOD"
    assert description.exterior_perimeter_in_miles == pytest.approx(551.47, rel=0.01)
    assert description.incident_type == "WF"
    assert (
        description.incident_complexity == "Type 4 Incident; Type 5 Incident; Type 3 IC"
    )
    assert (
        description.fuel_model
        == "Timber (Litter and Understory); Brush (2 feet); GS1; Grass"
    )
    assert description.fire_behavior == "Active; Creeping; Smoldering; Running"
    assert description.landowner_category == "Federal"


def test_fire_description_falls_back_to_point_when_perimeter_missing() -> None:
    entry = fire_index_entry("Bug", "active", identifier="id-bug")
    empty_perimeters = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-bug"],
            "fire_name": ["Bug"],
            "source": [None],
            "mission": [None],
            "area_acres": [None],
            "percent_contained": [None],
            "estimated_cost_to_date": [None],
            "estimated_final_cost": [None],
            "discovery_time": [None],
            "observation_time": [None],
            "source_attributes": [json.dumps({})],
        },
        geometry=[square(1.0)],
        crs="EPSG:4326",
    )
    description = peri_scribe.kml.fire_description(
        entry,
        empty_perimeters,
        description_point_frame(),
    )
    assert description.area_in_acres == pytest.approx(30.0)
    assert description.percent_contained == pytest.approx(30.0)
    assert description.estimated_cost_to_date_in_dollars == pytest.approx(3000.0)
    assert description.estimated_final_cost_in_dollars == pytest.approx(3500.0)
    assert description.observation_time == datetime.datetime(
        2026,
        8,
        6,
        20,
        0,
        tzinfo=datetime.UTC,
    )
    assert description.initial_response_time == datetime.datetime(
        2026,
        7,
        27,
        19,
        24,
        tzinfo=datetime.UTC,
    )
    assert description.exterior_perimeter_in_miles == pytest.approx(275.75, rel=0.01)
    assert description.incident_type == "WF"
    assert (
        description.incident_complexity == "Type 4 Incident; Type 5 Incident; Type 3 IC"
    )
    assert description.fuel_model == "Brush (2 feet); GS1; Grass"
    assert description.fire_behavior == "Active; Creeping; Smoldering"
    assert description.landowner_category is None


def test_fire_description_falls_back_to_protecting_agency() -> None:
    entry = fire_index_entry("Bug", "active", identifier="id-bug")
    point_frame = geopandas.GeoDataFrame(
        {
            "fire_identifier": ["id-bug"],
            "fire_name": ["Bug"],
            "source_attributes": [json.dumps({"POOJurisdictionalAgency": "BLM"})],
        },
        geometry=[shapely.geometry.Point(1.0, 1.0)],
        crs="EPSG:4326",
    )
    description = peri_scribe.kml.fire_description(
        entry,
        geometry_frame([]),
        point_frame,
    )
    assert description.protecting_unit == "BLM"
    assert description.exterior_perimeter_in_miles is None


def test_polygon_geometry_sets_description() -> None:
    kml = simplekml.Kml()
    peri_scribe.kml.polygon_geometry(
        kml.document,
        "Bug",
        "#perimeter-fill",
        square(1.0),
        0,
        description="description text",
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    assert placemark.findtext(kml_tag("description")) == "description text"


def test_multi_polygon_geometry_sets_description() -> None:
    kml = simplekml.Kml()
    multi_polygon = shapely.geometry.MultiPolygon([square(1.0), square(2.0)])
    peri_scribe.kml.multi_polygon_geometry(
        kml.document,
        "Bug",
        "#perimeter-fill",
        multi_polygon,
        0,
        description="description text",
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    assert placemark.findtext(kml_tag("description")) == "description text"


def test_point_placemark_sets_description() -> None:
    kml = simplekml.Kml()
    peri_scribe.kml.point_placemark(
        kml.document,
        "Bug",
        "#point-icon",
        shapely.geometry.Point(1.0, 1.0),
        0,
        description="description text",
    )
    placemark = placemark_named(document_from(kml.kml()), "Bug")
    assert placemark.findtext(kml_tag("description")) == "description text"


def test_fire_folder_applies_description_to_every_placemark(
    style_urls: dict[str, str],
) -> None:
    fire = peri_scribe.kml.FireGeometry(
        name="Bug",
        status=peri_scribe.models.FireStatus.ACTIVE,
        point=shapely.geometry.Point(1.0, 1.0),
        perimeters=(perimeter_with_time(square(1.0)),),
        description="<![CDATA[<b>Bug</b>]]>",
    )
    kml = simplekml.Kml()
    peri_scribe.kml.fire_folder(kml.document, fire, style_urls)
    folder = folder_named(document_from(kml.kml()), "Bug")
    assert placemark_names(folder) == ["Bug", "Unknown Mapping"]
    interior_folder = folder_named(folder, "Interior")
    assert placemark_names(interior_folder) == ["Interior"]
    for container in (folder, interior_folder):
        for name in placemark_names(container):
            assert placemark_named(container, name).findtext(
                kml_tag("description"),
            ) == ("<b>Bug</b>")
