"""Replay source query interleavings against the real snapshot collector."""

from __future__ import annotations

import dataclasses
import pathlib
import re
import typing

import arcgis.features
import pytest

import peri_scribe.sources.feed_state
import peri_scribe.sources.feed_types
import peri_scribe.sources.fetching
import peri_scribe.sources.snapshots
import spatial_data.layers
import tests.helpers.doubles.arcgis
import tests.helpers.doubles.peri_scribe.sources.fetching
import tests.helpers.factories.peri_scribe.sources.fetching


if typing.TYPE_CHECKING:
    import geopandas


@dataclasses.dataclass(frozen=True, kw_only=True)
class CollectionCase:
    """Keep each checked query result and persisted observation together."""

    full: bool
    marker: int
    changed: tuple[int, ...]
    listed: tuple[int, ...]
    selected: tuple[int, ...]
    body: tuple[int, ...]
    response: tuple[int, ...]
    saved: tuple[int, ...]
    receipt: int
    remote: tuple[int, ...]
    remote_marker: int


def numbers(value: str) -> tuple[int, ...]:
    """Read the finite sequences and sets emitted by TLC without evaluating code.

    Args:
        value: Raw TLC text for a sequence or integer set.

    Returns:
        Integers in the emitted order.
    """
    return tuple(map(int, re.findall(r"\d+", value)))


def cases(states: list[dict[str, str]]) -> set[CollectionCase]:
    """Keep distinct completed first invocations, including post-query mutations.

    Args:
        states: All checked collection states.

    Returns:
        Executable query plans and the corresponding checked saved rows.
    """
    return {
        CollectionCase(
            full=state["full"] == "TRUE",
            marker=int(state["observedMarker"]),
            changed=numbers(state["changed"]),
            listed=numbers(state["listed"]),
            selected=numbers(state["selected"]),
            body=numbers(state["atBody"]),
            response=numbers(state["response"]),
            saved=numbers(state["saved"]),
            receipt=int(state["receipt"]),
            remote=numbers(state["remote"]),
            remote_marker=int(state["marker"]),
        )
        for state in states
        if state["phase"] == '"done"' and state["recovery"] == "FALSE"
    }


def features(
    versions: tuple[int, ...],
) -> dict[
    int,
    tests.helpers.factories.peri_scribe.sources.fetching.FetchFeature,
]:
    """Give each abstract row version distinct attributes and stable point geometry.

    Args:
        versions: Version per object, where zero denotes an absent source row.

    Returns:
        Complete raw observations in the production feed schema.
    """
    return {
        identifier: tests.helpers.factories.peri_scribe.sources.fetching.FetchFeature(
            name=f"version{version}",
            active=False,
            modified_minute=0,
            longitude=-120 + identifier,
        )
        for identifier, version in enumerate(versions, 1)
        if version
    }


class QueryInterleaving(tests.helpers.doubles.arcgis.FeatureLayerStubBase):
    """Expose independently captured ID queries and a later feature response."""

    def __init__(self, case: CollectionCase) -> None:
        """Represent one finite source trace without contacting a service.

        Args:
            case: The TLC state containing each query's observed result.
        """
        super().__init__("https://example.test/FeatureServer/0", object())
        self.case = case
        self.queries: list[str] = []

    def query(self, **kwargs: object) -> arcgis.features.FeatureSet | dict[str, object]:
        """Validate real query routing before returning its checked source response.

        Args:
            kwargs: Parameters generated by the production collection code.

        Returns:
            The selected IDs or raw features from the corresponding source view.
        """
        if kwargs.get("return_ids_only"):
            where = str(kwargs["where"])
            self.queries.append("ids" if where == "1=1" else "changed")
            return {
                "objectIds": self.case.listed if where == "1=1" else self.case.changed,
            }
        self.queries.append("body")
        if not self.case.full:
            assert numbers(str(kwargs["object_ids"])) == self.case.selected
        chosen = (
            self.case.body
            if self.case.full
            else tuple(
                version if identifier in self.case.selected else 0
                for identifier, version in enumerate(self.case.body, 1)
            )
        )
        assert chosen == self.case.response
        return arcgis.features.FeatureSet([
            arcgis.features.Feature(
                attributes=tests.helpers.factories.peri_scribe.sources.fetching.fetch_attributes(
                    identifier,
                    feature,
                ),
                geometry={
                    "x": feature.longitude,
                    "y": 0,
                    "spatialReference": {"wkid": 4326},
                },
            )
            for identifier, feature in features(chosen).items()
        ])


def versions(dataframe: geopandas.GeoDataFrame | None) -> tuple[int, ...]:
    """Expose persisted names as row versions while asserting identity and geometry.

    Args:
        dataframe: The real current-state reader's result.

    Returns:
        Versions ordered by object ID, with zero for missing observations.
    """
    assert dataframe is not None
    found = {}
    for _index, row in dataframe.iterrows():
        identifier = int(row["OBJECTID"])
        assert row.geometry.x == -120 + identifier
        assert row.geometry.y == 0
        found[identifier] = int(str(row["name"]).removeprefix("version"))
    assert len(found) == len(dataframe)
    return tuple(found.get(identifier, 0) for identifier in (1, 2))


def replay_case(case: CollectionCase, directory: pathlib.Path) -> tuple[int, ...]:
    """Exercise the whole collector with real snapshot and current-state files.

    Args:
        case: First-invocation TLC outcome plus the final remote state.
        directory: Isolated application root.

    Returns:
        Current stored versions after the post-quiescence full fetch.
    """
    with pytest.MonkeyPatch.context() as patch:
        feed = tests.helpers.doubles.peri_scribe.sources.fetching.FeedStub(
            name="snapshot_collection",
            url="https://example.test/FeatureServer/0",
            last_edit_timestamp=case.marker,
        )
        source_directory = peri_scribe.sources.snapshots.source_directory_path(
            directory,
            2026,
            feed.name,
        )
        previous = (
            source_directory
            / peri_scribe.sources.snapshots.SourceFile(
                serial_number=0,
                last_edit_timestamp=1,
            ).relative_path
        )
        previous.parent.mkdir(parents=True)
        spatial_data.layers.write_geopackage(
            previous,
            [
                spatial_data.layers.LayerData(
                    name=feed.name,
                    dataframe=tests.helpers.factories.peri_scribe.sources.fetching.fetch_frame(
                        features((1, 0)),
                    ),
                ),
            ],
        )
        layer = QueryInterleaving(case)
        patch.setattr(arcgis.features, "FeatureLayer", lambda *_args: layer)
        patch.setattr(
            peri_scribe.sources.fetching,
            "open_feed_connection",
            lambda _: None,
        )
        outcome = peri_scribe.sources.fetching.fetch_feed_snapshot(
            typing.cast("peri_scribe.sources.feed_types.Feed", feed),
            base_dir=directory,
            year=2026,
            full=case.full,
        )
        current = peri_scribe.sources.feed_state.read_current_features(
            source_directory,
            typing.cast("peri_scribe.sources.feed_types.Feed", feed),
        )
        assert versions(current) == case.saved
        assert outcome.changed == (case.saved != (1, 0))
        sources = peri_scribe.sources.snapshots.existing_source_files(source_directory)
        assert sources[-1].last_edit_timestamp == case.receipt
        expected_queries = (
            ["body"] if case.full else [] if case.marker == 1 else ["changed", "ids"]
        )
        if not case.full and case.selected:
            expected_queries.append("body")
        assert layer.queries == expected_queries
        assert (outcome.error is not None) == (
            bool(case.selected) and case.response == (0, 0)
        )
        recovery = dataclasses.replace(
            case,
            full=True,
            body=case.remote,
            response=case.remote,
        )
        layer = QueryInterleaving(recovery)
        stable_feed = dataclasses.replace(feed, last_edit_timestamp=case.remote_marker)
        peri_scribe.sources.fetching.fetch_feed_snapshot(
            typing.cast("peri_scribe.sources.feed_types.Feed", stable_feed),
            base_dir=directory,
            year=2026,
            full=True,
        )
        return versions(
            peri_scribe.sources.feed_state.read_current_features(
                source_directory,
                typing.cast("peri_scribe.sources.feed_types.Feed", stable_feed),
            ),
        )
